### ISSUE TITLE
最新的版本使用train_rm.py训练reward model报错

### ISSUE THREAD

**Issue by authurlord** [hiyouga/ChatGLM-Efficient-Tuning#104]
错误信息如下：Traceback (most recent call last):
  File "/home/user/KGC/ChatGLM-Efficient-Tuning/src/train_rm.py", line 57, in <module>
    main()
  File "/home/user/KGC/ChatGLM-Efficient-Tuning/src/train_rm.py", line 42, in main
    train_result = trainer.train()
  File "/home/user/anaconda3/envs/GLM/lib/python3.9/site-packages/transformers/trainer.py", line 1664, in train
    return inner_training_loop(
  File "/home/user/anaconda3/envs/GLM/lib/python3.9/site-packages/transformers/trainer.py", line 1909, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/home/user/anaconda3/envs/GLM/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/home/user/anaconda3/envs/GLM/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 678, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/user/anaconda3/envs/GLM/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/home/user/KGC/ChatGLM-Efficient-Tuning/src/utils/pairwise.py", line 39, in __call__
    "attention_mask": self.get_attention_masks(input_ids),
TypeError: get_attention_masks() missing 1 required positional argument: 'device'

这个错误在之前的版本中没有出现，似乎是src/utils/data_collador.py中新引入的get_attention_masks函数在src/utils/pairwise.py中的调用所引起的，能够麻烦测试一下目前的train_rm.py能否正常使用？

**Comment by authurlord** [comment]
使用accelerate在4gpu下训练

**Comment by hiyouga** [comment]
已修复。
