### ISSUE TITLE
多卡sft跑到30%的时候报错，重试了好几次都会中途报错

### ISSUE THREAD

**Issue by Tungsong** [hiyouga/ChatGLM-Efficient-Tuning#105]
报错信息如下
`Traceback (most recent call last):
  File "/root/anaconda3/envs/chatglm-finetune/lib/python3.10/site-packages/torch/random.py", line 125, in fork_rng
    yield
  File "/root/anaconda3/envs/chatglm-finetune/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 141, in backward
    outputs = ctx.run_function(*detached_inputs)
  File "/root/anaconda3/envs/chatglm-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b/modeling_chatglm.py", line 627, in forward
    attention_outputs = self.attention(
  File "/root/anaconda3/envs/chatglm-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b/modeling_chatglm.py", line 460, in forward
    cos, sin = self.rotary_emb(q1, seq_len=position_ids.max() + 1)
  File "/root/anaconda3/envs/chatglm-finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b/modeling_chatglm.py", line 202, in forward
    t = torch.arange(seq_len, device=x.device, dtype=self.inv_freq.dtype)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/dbbd/ChatGLM-Efficient-Tuning-for-tungsong/src/train_sft.py", line 85, in <module>
    main()
  File "/usr/local/dbbd/ChatGLM-Efficient-Tuning-for-tungsong/src/train_sft.py", line 57, in main
    train_result = trainer.train()
  File "/root/anaconda3/envs/chatglm-finetune/lib/python3.10/site-packages/transformers/trainer.py", line 1662, in train
    return inner_training_loop(
  File "/root/anaconda3/envs/chatglm-finetune/lib/python3.10/site-packages/transformers/trainer.py", line 1929, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/anaconda3/envs/chatglm-finetune/lib/python3.10/site-packages/transformers/trainer.py", line 2709, in training_step
    self.scaler.scale(loss).backward()
  File "/root/anaconda3/envs/chatglm-finetune/lib/python3.10/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/root/anaconda3/envs/chatglm-finetune/lib/python3.10/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/root/anaconda3/envs/chatglm-finetune/lib/python3.10/site-packages/torch/autograd/function.py", line 267, in apply
    return user_fn(self, *args)
  File "/root/anaconda3/envs/chatglm-finetune/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 132, in backward
    with torch.random.fork_rng(devices=rng_devices, enabled=ctx.preserve_rng_state):
  File "/root/anaconda3/envs/chatglm-finetune/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/anaconda3/envs/chatglm-finetune/lib/python3.10/site-packages/torch/random.py", line 129, in fork_rng
    torch.cuda.set_rng_state(gpu_rng_state, device)
  File "/root/anaconda3/envs/chatglm-finetune/lib/python3.10/site-packages/torch/cuda/random.py", line 64, in set_rng_state
    _lazy_call(cb)
  File "/root/anaconda3/envs/chatglm-finetune/lib/python3.10/site-packages/torch/cuda/__init__.py", line 165, in _lazy_call
    callable()
  File "/root/anaconda3/envs/chatglm-finetune/lib/python3.10/site-packages/torch/cuda/random.py", line 62, in cb
    default_generator.set_state(new_state_copy)
RuntimeError: false INTERNAL ASSERT FAILED at "../c10/cuda/CUDAGraphsC10Utils.h":73, please report a bug to PyTorch. Unknown CUDA graph CaptureStatus32528
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:31 (most recent call first):

WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1016993 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 1016992) of binary: /root/anaconda3/envs/chatglm-finetune/bin/python
Traceback (most recent call last):
  File "/root/anaconda3/envs/chatglm-finetune/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/chatglm-finetune/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/root/anaconda3/envs/chatglm-finetune/lib/python3.10/site-packages/accelerate/commands/launch.py", line 909, in launch_command
    multi_gpu_launcher(args)
  File "/root/anaconda3/envs/chatglm-finetune/lib/python3.10/site-packages/accelerate/commands/launch.py", line 604, in multi_gpu_launcher
    distrib_run.run(args)
  File "/root/anaconda3/envs/chatglm-finetune/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/root/anaconda3/envs/chatglm-finetune/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/anaconda3/envs/chatglm-finetune/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
========================================================
src/train_sft.py FAILED
--------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
--------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-18_20:25:07
  host      : uni-dzkf-gpu
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 1016992)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 1016992
========================================================
`

**Comment by hiyouga** [comment]
可能和 accelerate 的设置有关，提供一下配置文件。

**Comment by Tungsong** [comment]
> 可能和 accelerate 的设置有关，提供一下配置文件。

compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

**Comment by hiyouga** [comment]
我使用相同的配置文件无法复现出错误，暂时无法提供更多帮助。

**Comment by Benstime** [comment]
我也有相同的问题, 使用的是zero2的配置.

**Comment by Tungsong** [comment]
玄学，没有任何改动，最近一次跑又没问题了
