### ISSUE TITLE
多卡训练报错

### ISSUE THREAD

**Issue by sungh66** [hiyouga/ChatGLM-Efficient-Tuning#114]
使用accelrate多卡训练config如下：

Do you wish to optimize your script with torch dynamo?[yes/NO]:yes                                                                                              
----------------------------------------------------------------------------------------------------------------------------------------------------------------Which dynamo backend would you like to use?                                                                                                                     
inductor                                                                                                                                                        
Do you want to customize the defaults sent to torch.compile? [yes/NO]: no                                                                                       
Do you want to use DeepSpeed? [yes/NO]:                                                                                                                         
Do you want to use FullyShardedDataParallel? [yes/NO]:                                                                                                          
Do you want to use Megatron-LM ? [yes/NO]: yes                                                                                                                  
What is the Tensor Parallelism degree/size? [1]:2                                                                                                               
Do you want to enable Sequence Parallelism? [YES/no]:                                                                                                           
What is the Pipeline Parallelism degree/size? [1]:2                                                                                                             
What is the number of micro-batches? [1]:2                                                                                                                      
Do you want to enable selective activation recomputation? [YES/no]:                                                                                             
Do you want to use distributed optimizer which shards optimizer state and gradients across data pralellel ranks? [YES/no]:                                      
What is the gradient clipping value based on global L2 Norm (0 to disable)? [1.0]: 
How many GPU(s) should be used for distributed training? [1]:4
数据、权重方面没问题了
运行后的报错如下：
[INFO|trainer.py:621] 2023-05-25 01:05:09,826 >> Using cuda_amp half precision backend
[INFO|trainer.py:1769] 2023-05-25 01:05:09,982 >> ***** Running training *****
[INFO|trainer.py:1770] 2023-05-25 01:05:09,982 >>   Num examples = 48,818
[INFO|trainer.py:1771] 2023-05-25 01:05:09,982 >>   Num Epochs = 3
[INFO|trainer.py:1772] 2023-05-25 01:05:09,982 >>   Instantaneous batch size per device = 4
[INFO|trainer.py:1773] 2023-05-25 01:05:09,982 >>   Total train batch size (w. parallel, distributed & accumulation) = 64
[INFO|trainer.py:1774] 2023-05-25 01:05:09,982 >>   Gradient Accumulation steps = 4
[INFO|trainer.py:1775] 2023-05-25 01:05:09,982 >>   Total optimization steps = 2,289
[INFO|trainer.py:1776] 2023-05-25 01:05:09,983 >>   Number of trainable parameters = 3,670,016
  0%|                                                                                                                                  | 0/2289 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/root/llm/chatglm/ChatGLM-Efficient-Tuning/src/train_sft.py", line 94, in <module>
    main()
  File "/root/llm/chatglm/ChatGLM-Efficient-Tuning/src/train_sft.py", line 66, in main
    train_result = trainer.train()
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/transformers/trainer.py", line 1662, in train
    return inner_training_loop(
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/transformers/trainer.py", line 1929, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/transformers/trainer.py", line 2709, in training_step
    self.scaler.scale(loss).backward()
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 157, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 55 has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration. You can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print parameter names for further debugging.
Traceback (most recent call last):
  File "/root/llm/chatglm/ChatGLM-Efficient-Tuning/src/train_sft.py", line 94, in <module>
    main()
  File "/root/llm/chatglm/ChatGLM-Efficient-Tuning/src/train_sft.py", line 66, in main
    train_result = trainer.train()
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/transformers/trainer.py", line 1662, in train
    return inner_training_loop(
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/transformers/trainer.py", line 1929, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/transformers/trainer.py", line 2709, in training_step
    self.scaler.scale(loss).backward()
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 157, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 55 has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration. You can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print parameter names for further debugging.
Traceback (most recent call last):
  File "/root/llm/chatglm/ChatGLM-Efficient-Tuning/src/train_sft.py", line 94, in <module>
    main()
  File "/root/llm/chatglm/ChatGLM-Efficient-Tuning/src/train_sft.py", line 66, in main
    train_result = trainer.train()
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/transformers/trainer.py", line 1662, in train
    return inner_training_loop(
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/transformers/trainer.py", line 1929, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/transformers/trainer.py", line 2709, in training_step
    self.scaler.scale(loss).backward()
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 157, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 55 has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration. You can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print parameter names for further debugging.
  0%|                                                                                                                                  | 0/2289 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/root/llm/chatglm/ChatGLM-Efficient-Tuning/src/train_sft.py", line 94, in <module>
    main()
  File "/root/llm/chatglm/ChatGLM-Efficient-Tuning/src/train_sft.py", line 66, in main
    train_result = trainer.train()
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/transformers/trainer.py", line 1662, in train
    return inner_training_loop(
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/transformers/trainer.py", line 1929, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/transformers/trainer.py", line 2709, in training_step
    self.scaler.scale(loss).backward()
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 157, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 55 has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration. You can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print parameter names for further debugging.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 9712) of binary: /root/anaconda3/envs/chatglm/bin/python
Traceback (most recent call last):
  File "/root/anaconda3/envs/chatglm/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/accelerate/commands/launch.py", line 907, in launch_command
    multi_gpu_launcher(args)
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/accelerate/commands/launch.py", line 604, in multi_gpu_launcher
    distrib_run.run(args)
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
src/train_sft.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-05-25_01:05:20
  host      : GPU-27
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 9713)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-05-25_01:05:20
  host      : GPU-27
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 9714)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2023-05-25_01:05:20
  host      : GPU-27
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 9715)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-25_01:05:20
  host      : GPU-27
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 9712)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

错误是ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1)
如何更改config？或者和环境依赖有关？

**Comment by hiyouga** [comment]
https://github.com/hiyouga/ChatGLM-Efficient-Tuning/wiki/%E5%B8%B8%E8%A7%81%E6%8A%A5%E9%94%99%E4%BF%A1%E6%81%AF%E6%B1%87%E6%80%BB#runtimeerror-expected-to-mark-a-variable-ready-only-once

**Comment by sungh66** [comment]
> https://github.com/hiyouga/ChatGLM-Efficient-Tuning/wiki/%E5%B8%B8%E8%A7%81%E6%8A%A5%E9%94%99%E4%BF%A1%E6%81%AF%E6%B1%87%E6%80%BB#runtimeerror-expected-to-mark-a-variable-ready-only-once

已解决，谢谢

**Comment by lucheng07082221** [comment]
请问如何解决的阿
