### ISSUE TITLE
多卡sft中途报错

### ISSUE THREAD

**Issue by MingJiaAn** [hiyouga/ChatGLM-Efficient-Tuning#129]
WARNING:torch.distributed.elastic.agent.server.api:Received 1 death signal, shutting down workers
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 94877 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 94878 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 94879 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 94880 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 94881 closing signal SIGHUP
Traceback (most recent call last):
  File "/mnt/envs/glm_rlhf/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/mnt/envs/glm_rlhf/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/mnt/envs/glm_rlhf/lib/python3.10/site-packages/accelerate/commands/launch.py", line 909, in launch_command
    multi_gpu_launcher(args)
  File "/mnt/envs/glm_rlhf/lib/python3.10/site-packages/accelerate/commands/launch.py", line 604, in multi_gpu_launcher
    distrib_run.run(args)
  File "/mnt/envs/glm_rlhf/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/mnt/envs/glm_rlhf/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/envs/glm_rlhf/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 237, in launch_agent
    result = agent.run()
  File "/mnt/envs/glm_rlhf/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/mnt/envs/glm_rlhf/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 709, in run
    result = self._invoke_run(role)
  File "/mnt/envs/glm_rlhf/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 850, in _invoke_run
    time.sleep(monitor_interval)
  File "/mnt/envs/glm_rlhf/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 62, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 94802 got signal: 1

训练数据量比较大，350w条左右，每次训练途中都会报错

**Comment by jet-yangqs** [comment]
之前遇到相同问题是因为数据集中有文本较长的样本，导致OOM。通过调小batchsize和max_source_length可以解决

**Comment by MingJiaAn** [comment]
> 之前遇到相同问题是因为数据集中有文本较长的样本，导致OOM。通过调小batchsize和max_source_length可以解决

请问您max_source_length取的是多少呢？

**Comment by MingJiaAn** [comment]
> 之前遇到相同问题是因为数据集中有文本较长的样本，导致OOM。通过调小batchsize和max_source_length可以解决

我看max_source_length默认是512，是默认的太长了吗？batch size的话我最小的时候设的是2，都会报错，是4个V100的卡

**Comment by hiyouga** [comment]
设置 `--max_source_length 256` 试试。

**Comment by MingJiaAn** [comment]
> 设置 `--max_source_length 256` 试试。

同样会报错
