### ISSUE TITLE
OOM Error when saving models trained in INT8 mode

### ISSUE THREAD

**Issue by hiyouga** [hiyouga/ChatGLM-Efficient-Tuning#13]
A bug report from the WeChat group:
```
04/20/2023 11:04:39 - INFO - utils .common - Saving model checkpoint to path_to_checkpoint
Traceback (most recent call last):
  File "/src/finetune.py", line 73, in <module>
    main()
  File "/src/finetune.py", line 55, in main
    trainer.save_model()
  File "/site-packages/transformers/trainer.py", line 2830, in save_model
    self._save(output_dir)
  File "src/utils/common.py", line 462, in _save
    self.model.save_pretrained(output_dir) # only save peft weights with the built-in method
  File "/peft/src/peft/peft_model.py", line 116, in save_pretrained
    output_state_dict = get_peft_model_state_dict(
  File "/peft/src/peft/utils/save_and_load.py", line 32, in get_peft_model_state_dict
    state_dict = model.state_dict()
  File "/torch/nn/modules/module.py", line 1818, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  File "/torch/nn/modules/module.py", line 1818, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  File "/torch/nn/modules/module.py", line 1818, in state_dict
      [Previous line repeated 4 more times]
  File "/torch/nn/modules/module.py", line 1815, in state_dict
    self._save_to_state_dict(destination, prefix, keep_vars)
  File "/bitsandbytes/nn/modules.py", line 268, in _save to_state_dict
    self.weight.data = undo_layout(self.state.CxB, self.state.tile_indices)
  File "/bitsandbytes/autograd/_functions.py", line 96, in undo_layout
    outputs = torch.empty_like(tensor) # note: not using .index_copy because it was slower on cuda
torch.cuda.OutofMemoryError: CUDA out of memory, Tried to allocate 64.00 MiB (GPU 0: 14,76 GiB total capacity; 13.82 GiB already allocated; 47.75 MiB free; 14.02 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

A similar report can be found at: https://github.com/huggingface/peft/issues/335

I suppose the failure is caused by `state_dict = model.state_dict()`.

**Comment by hiyouga** [comment]
This problem is related to the `bitsandbytes 0.38.x`. Going back to 0.37.2 version should address it.
https://github.com/TimDettmers/bitsandbytes/issues/324
