### ISSUE TITLE
模型微调时单卡正常，但是多卡会报错Caught RuntimeError in replica 0 on device 0.

### ISSUE THREAD

**Issue by Congcong-Song** [hiyouga/ChatGLM-Efficient-Tuning#136]

**Comment by Congcong-Song** [comment]
如图：
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/78061552/3d63123c-37d2-411c-abe5-32e0724c9a53)

**Comment by hiyouga** [comment]
提供一下多卡运行的命令行参数。

**Comment by Congcong-Song** [comment]
命令行参数：
CUDA_VISIBLE_DEVICES=2,3 \
python src/train_sft.py   \
    --do_train \
    --dataset demo_100\
    --finetuning_type lora \
    --output_dir output/demo100_lora_int8_e1_gpu2\
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 100 \
    --learning_rate 5e-5 \
    --num_train_epochs 1.0 \
    --fp16   \
    --quantization_bit 8
    
报错：
Traceback (most recent call last):
  File "/home/inspur/scc/gpt/ChatGLM-Efficient-Tuning/src/train_sft.py", line 101, in <module>
    main()
  File "/home/inspur/scc/gpt/ChatGLM-Efficient-Tuning/src/train_sft.py", line 69, in main
    train_result = trainer.train()
  File "/home/inspur/anaconda3/envs/llm_py39/lib/python3.9/site-packages/transformers/trainer.py", line 1633, in train
    return inner_training_loop(
  File "/home/inspur/anaconda3/envs/llm_py39/lib/python3.9/site-packages/transformers/trainer.py", line 1902, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/inspur/anaconda3/envs/llm_py39/lib/python3.9/site-packages/transformers/trainer.py", line 2645, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/inspur/anaconda3/envs/llm_py39/lib/python3.9/site-packages/transformers/trainer.py", line 2677, in compute_loss
    outputs = model(**inputs)
  File "/home/inspur/anaconda3/envs/llm_py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/inspur/anaconda3/envs/llm_py39/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 171, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/inspur/anaconda3/envs/llm_py39/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 181, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/inspur/anaconda3/envs/llm_py39/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 89, in parallel_apply
    output.reraise()
  File "/home/inspur/anaconda3/envs/llm_py39/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 1 on device 1.

**Comment by Congcong-Song** [comment]
报错补充：module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cuda:1

**Comment by hiyouga** [comment]
多卡微调请使用 Accelerate，参考 readme.md。

**Comment by Congcong-Song** [comment]
使用accelerate会报错：

Traceback (most recent call last):
  File "/home/inspur/scc/gpt/ChatGLM-Efficient-Tuning/src/train_sft.py", line 101, in <module>
Traceback (most recent call last):
  File "/home/inspur/scc/gpt/ChatGLM-Efficient-Tuning/src/train_sft.py", line 101, in <module>
    main()
  File "/home/inspur/scc/gpt/ChatGLM-Efficient-Tuning/src/train_sft.py", line 24, in main
        model_args, data_args, training_args, finetuning_args = prepare_args(stage="sft")main()

  File "/home/inspur/scc/gpt/ChatGLM-Efficient-Tuning/src/utils/common.py", line 258, in prepare_args
  File "/home/inspur/scc/gpt/ChatGLM-Efficient-Tuning/src/train_sft.py", line 24, in main
    model_args, data_args, training_args, finetuning_args = prepare_args(stage="sft")
  File "/home/inspur/scc/gpt/ChatGLM-Efficient-Tuning/src/utils/common.py", line 258, in prepare_args
    model_args, data_args, training_args, finetuning_args = parser.parse_args_into_dataclasses()
  File "/home/inspur/anaconda3/envs/llm_py39/lib/python3.9/site-packages/transformers/hf_argparser.py", line 341, in parse_args_into_dataclasses
    model_args, data_args, training_args, finetuning_args = parser.parse_args_into_dataclasses()
  File "/home/inspur/anaconda3/envs/llm_py39/lib/python3.9/site-packages/transformers/hf_argparser.py", line 341, in parse_args_into_dataclasses
    raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}")
ValueError: Some specified arguments are not used by the HfArgumentParser: [' ']
    raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}")
ValueError: Some specified arguments are not used by the HfArgumentParser: [' ']
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 4680) of binary: /home/inspur/anaconda3/envs/llm_py39/bin/python
Traceback (most recent call last):
  File "/home/inspur/anaconda3/envs/llm_py39/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/inspur/anaconda3/envs/llm_py39/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/inspur/anaconda3/envs/llm_py39/lib/python3.9/site-packages/accelerate/commands/launch.py", line 909, in launch_command
    multi_gpu_launcher(args)
  File "/home/inspur/anaconda3/envs/llm_py39/lib/python3.9/site-packages/accelerate/commands/launch.py", line 604, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/inspur/anaconda3/envs/llm_py39/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/inspur/anaconda3/envs/llm_py39/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/inspur/anaconda3/envs/llm_py39/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by hiyouga** [comment]
你输入的命令行参数有问题，请检查格式。

**Comment by Congcong-Song** [comment]
我的命令行参数是：
CUDA_VISIBLE_DEVICES=2,3 accelerate launch src/train_sft.py     --do_train     --finetuning_type lora     --gradient_accumulation_steps 4     --lr_scheduler_type cosine     --logging_steps 10     --learning_rate 5e-5     --fp16       --quantization_bit 8      --ddp_find_unused_parameters False      --num_train_epochs 1.0     --per_device_train_batch_size 1     --dataset demo_100      --output_dir output/demo100_lora_int8_e1_gpu23    --save_steps 100 

我的加速配置是：
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: 2,3
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

最后的问题：
程序运行的时候卡住了
[INFO|modeling_utils.py:2514] 2023-06-06 03:24:17,199 >> Detected 8-bit loading: activating 8-bit loading for this model
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:15<00:00,  1.92s/it]
[INFO|modeling_utils.py:3034] 2023-06-06 03:24:55,985 >> All model checkpoint weights were used when initializing ChatGLMForConditionalGeneration.

[INFO|modeling_utils.py:3042] 2023-06-06 03:24:55,985 >> All the weights of ChatGLMForConditionalGeneration were initialized from the model checkpoint at /home/inspur/pretrained/THUDM/chatglm-6b.
If your task is similar to the task the model of the checkpoint was trained on, you can already use ChatGLMForConditionalGeneration for predictions without further training.
[INFO|modeling_utils.py:2692] 2023-06-06 03:24:55,991 >> Generation config file not found, using a generation config created from the model config.
06/06/2023 03:24:56 - INFO - utils.common - Fine-tuning method: LoRA
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:15<00:00,  1.91s/it]
06/06/2023 03:24:56 - INFO - utils.common - Fine-tuning method: LoRA
06/06/2023 03:25:06 - INFO - utils.common - Quantized model to 8 bit.
trainable params: 3670016 || all params: 6176956416 || trainable%: 0.0594
Running tokenizer on dataset:   0%|                                                                                                              | 0/100 [00:00<?, ? examples/s]06/06/2023 03:25:06 - INFO - datasets.arrow_dataset - Caching processed dataset at /home/inspur/.cache/huggingface/datasets/json/default-a3425fd88cf3e7f2/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4/cache-d6562321e02c69cf.arrow
input_ids:                                                                                                                                                                      
[5, 115832, 58, 67432, 99202, 102774, 65564, 125907, 67432, 99202, 102774, 65564, 68130, 64829, 72914, 65564, 6, 65256, 63888, 9, 18, 15, 16, 77767, 64780, 64168, 76791, 64829, 63823, 63942, 65620, 64039, 64404, 64213, 66527, 66390, 65342, 63826, 76320, 63824, 106749, 71664, 63824, 106749, 79623, 111009, 63824, 69105, 96292, 63824, 67432, 99202, 63823, 63899, 102774, 65564, 64544, 67568, 64090, 63831, 64090, 75990, 6, 63843, 67568, 64541, 64118, 101525, 75990, 6, 68130, 72350, 106800, 64291, 6, 106907, 58, 67432, 99202, 68802, 125907, 130001, 130004, 48, 67432, 99202, 102774, 65564, 62, 68130, 64829, 72914, 65564, 6, 65620, 64039, 64404, 64213, 66527, 66390, 65342, 63826, 76320, 63824, 106749, 71664, 63824, 106749, 79623, 111009, 63824, 69105, 96292, 63824, 67432, 99202, 6, 68130, 72350, 106800, 64291, 63823, 130005]
inputs:
解释一下“和平共处五项原则”。和平共处五项原则是中国提出的政治原则,第一次于1954年在亚非会议上提出。它强调国家间应该互相尊重独立和主权、互不侵犯、互不干涉内政、平等互利、和平共处。这五项原则不仅适用于国与国之间的关系,也适用于国内各族群之间的关系,是中国外交的基本原则之一,也被称为“和平共处之道”。 “和平共处五项原则”是中国提出的政治原则,强调国家间应该互相尊重独立和主权、互不侵犯、互不干涉内政、平等互利、和平共处,是中国外交的基本原则之一。
label_ids:
[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 130004, 48, 67432, 99202, 102774, 65564, 62, 68130, 64829, 72914, 65564, 6, 65620, 64039, 64404, 64213, 66527, 66390, 65342, 63826, 76320, 63824, 106749, 71664, 63824, 106749, 79623, 111009, 63824, 69105, 96292, 63824, 67432, 99202, 6, 68130, 72350, 106800, 64291, 63823, 130005]
labels:
<image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100> “和平共处五项原则”是中国提出的政治原则,强调国家间应该互相尊重独立和主权、互不侵犯、互不干涉内政、平等互利、和平共处,是中国外交的基本原则之一。
06/06/2023 03:25:06 - INFO - utils.common - Quantized model to 8 bit.
trainable params: 3670016 || all params: 6176956416 || trainable%: 0.0594
[INFO|trainer.py:375] 2023-06-06 03:25:07,415 >> The model is loaded in 8-bit precision. To train this model you need to add additional modules inside the model such as adapters using `peft` library and freeze the model weights. Please check  the examples in https://github.com/huggingface/peft for more details.
[INFO|trainer.py:597] 2023-06-06 03:25:07,415 >> Using cuda_amp half precision backend
06/06/2023 03:25:07 - WARNING - datasets.arrow_dataset - Loading cached processed dataset at /home/inspur/.cache/huggingface/datasets/json/default-a3425fd88cf3e7f2/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4/cache-d6562321e02c69cf.arrow
input_ids:
[5, 115832, 58, 67432, 99202, 102774, 65564, 125907, 67432, 99202, 102774, 65564, 68130, 64829, 72914, 65564, 6, 65256, 63888, 9, 18, 15, 16, 77767, 64780, 64168, 76791, 64829, 63823, 63942, 65620, 64039, 64404, 64213, 66527, 66390, 65342, 63826, 76320, 63824, 106749, 71664, 63824, 106749, 79623, 111009, 63824, 69105, 96292, 63824, 67432, 99202, 63823, 63899, 102774, 65564, 64544, 67568, 64090, 63831, 64090, 75990, 6, 63843, 67568, 64541, 64118, 101525, 75990, 6, 68130, 72350, 106800, 64291, 6, 106907, 58, 67432, 99202, 68802, 125907, 130001, 130004, 48, 67432, 99202, 102774, 65564, 62, 68130, 64829, 72914, 65564, 6, 65620, 64039, 64404, 64213, 66527, 66390, 65342, 63826, 76320, 63824, 106749, 71664, 63824, 106749, 79623, 111009, 63824, 69105, 96292, 63824, 67432, 99202, 6, 68130, 72350, 106800, 64291, 63823, 130005]
inputs:
解释一下“和平共处五项原则”。和平共处五项原则是中国提出的政治原则,第一次于1954年在亚非会议上提出。它强调国家间应该互相尊重独立和主权、互不侵犯、互不干涉内政、平等互利、和平共处。这五项原则不仅适用于国与国之间的关系,也适用于国内各族群之间的关系,是中国外交的基本原则之一,也被称为“和平共处之道”。 “和平共处五项原则”是中国提出的政治原则,强调国家间应该互相尊重独立和主权、互不侵犯、互不干涉内政、平等互利、和平共处,是中国外交的基本原则之一。
label_ids:
[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 130004, 48, 67432, 99202, 102774, 65564, 62, 68130, 64829, 72914, 65564, 6, 65620, 64039, 64404, 64213, 66527, 66390, 65342, 63826, 76320, 63824, 106749, 71664, 63824, 106749, 79623, 111009, 63824, 69105, 96292, 63824, 67432, 99202, 6, 68130, 72350, 106800, 64291, 63823, 130005]
labels:
<image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100><image_-100> “和平共处五项原则”是中国提出的政治原则,强调国家间应该互相尊重独立和主权、互不侵犯、互不干涉内政、平等互利、和平共处,是中国外交的基本原则之一。

然后就不继续运行了，请问是我的配置还是命令有问题吗？

**Comment by hiyouga** [comment]
多卡使用量化可能会出现问题，请尝试更新代码和 bitsandbytes 库后重新实验，如果还是卡住就说明目前多卡和量化不能同时开启。

**Comment by Congcong-Song** [comment]
问题已经解决啦！ 
pip install transformers[torch]
