### ISSUE TITLE
RuntimeError when Running tokenizer on dataset 单机两卡遇到的问题，是因为数据量太大了吗？

### ISSUE THREAD

**Issue by JOHNNY-fans** [hiyouga/ChatGLM-Efficient-Tuning#137]
Running tokenizer on dataset: 47%|███████████████▊ | 3169000/6811963 [30:11<38:27, 1578.58 examples/s]Traceback (most recent call last):
File "/mnt/data/smart_health_02/fanyongqi/workspace/ChatMedNorm/src/train_sft.py", line 94, in
main()
File "/mnt/data/smart_health_02/fanyongqi/workspace/ChatMedNorm/src/train_sft.py", line 25, in main
dataset = preprocess_data(dataset, tokenizer, data_args, training_args, stage="sft")
File "/mnt/data/smart_health_02/fanyongqi/workspace/ChatMedNorm/src/utils/common.py", line 506, in preprocess_data
with training_args.main_process_first(desc="dataset map pre-processing"):
File "/mnt/data/smart_health_02/fanyongqi/anaconda3/envs/chatglm_etuning/lib/python3.9/contextlib.py", line 119, in enter
return next(self.gen)
File "/mnt/data/smart_health_02/fanyongqi/anaconda3/envs/chatglm_etuning/lib/python3.9/site-packages/transformers/training_args.py", line 1891, in main_process_first
torch.distributed.barrier()
File "/mnt/data/smart_health_02/fanyongqi/anaconda3/envs/chatglm_etuning/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 3328, in barrier
work = default_pg.barrier(opts=opts)
RuntimeError: [1] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Socket Timeout

**Comment by hiyouga** [comment]
是的，可能是内存满了。

**Comment by JOHNNY-fans** [comment]
> 是的，可能是内存满了。

感谢，已经解决了，是因为处理时间太久了，可能一直等待，导致异步出了问题，把num_worker开大以后就跑起来了，实测数据处理超过30min就会炸。
