### ISSUE TITLE
更新后LORA报错TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by XiaoruiQ** [hiyouga/ChatGLM-Efficient-Tuning#147]
上周的版本Lora和p_tuning都可以正常跑，今天git pull更新后p_tuning正常，lora报错，信息如下：
Traceback (most recent call last):
  File "/workspace/ChatGLM-Efficient-Tuning/src/train_sft.py", line 100, in <module>
    main()
  File "/workspace/ChatGLM-Efficient-Tuning/src/train_sft.py", line 25, in main
    model, tokenizer = load_pretrained(model_args, finetuning_args, training_args, training_args.do_train, stage="sft")
  File "/workspace/ChatGLM-Efficient-Tuning/src/utils/common.py", line 219, in load_pretrained
    model = init_adapter(model, model_args, finetuning_args, is_trainable)
  File "/workspace/ChatGLM-Efficient-Tuning/src/utils/common.py", line 100, in init_adapter
    assert os.path.exists(os.path.join(model_args.checkpoint_dir[0], CONFIG_NAME)), \
TypeError: 'NoneType' object is not subscriptable

**Comment by hiyouga** [comment]
已经修复，请更新代码。

**Comment by XiaoruiQ** [comment]
> 已经修复，请更新代码。
已解决，非常感谢。
