### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by neverstoplearn** [hiyouga/ChatGLM-Efficient-Tuning#148]
命令：
accelerate launch src/train_sft.py --do_train --dataset alpaca_gpt4_zh --finetuning_type lora --output_dir path_to_sft_checkpoint --per_device_train_batch_size 1 --gradient_accumulation_steps 4  --lr_scheduler_type cosine --logging_steps 10  --save_steps 1000  --learning_rate 5e-5 --num_train_epochs 3.0 --quantization_bit 8 --fp16
报错：
Traceback (most recent call last):
  File "/media/4674F27A74F26BD5/zx/ChatGLM-Efficient-Tuning/src/train_sft.py", line 100, in <module>
    main()
  File "/media/4674F27A74F26BD5/zx/ChatGLM-Efficient-Tuning/src/train_sft.py", line 68, in main
    train_result = trainer.train()
  File "/home/its/anaconda3/envs/LLM/lib/python3.9/site-packages/transformers/trainer.py", line 1664, in train
    return inner_training_loop(
  File "/home/its/anaconda3/envs/LLM/lib/python3.9/site-packages/transformers/trainer.py", line 1938, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/its/anaconda3/envs/LLM/lib/python3.9/site-packages/transformers/trainer.py", line 2745, in training_step
    self.scaler.scale(loss).backward()
  File "/home/its/anaconda3/envs/LLM/lib/python3.9/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/its/anaconda3/envs/LLM/lib/python3.9/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/its/anaconda3/envs/LLM/lib/python3.9/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/home/its/anaconda3/envs/LLM/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 157, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/home/its/anaconda3/envs/LLM/lib/python3.9/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/its/anaconda3/envs/LLM/lib/python3.9/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/home/its/anaconda3/envs/LLM/lib/python3.9/site-packages/bitsandbytes/autograd/_functions.py", line 476, in backward
    grad_A = torch.matmul(grad_output, CB).view(ctx.grad_shape).to(ctx.dtype_A)
RuntimeError: expected scalar type Half but found Float

**Comment by neverstoplearn** [comment]
请问如何修复，谢谢。

**Comment by hiyouga** [comment]
请问使用的是什么型号的 GPU？

**Comment by hiyouga** [comment]
Titan X 不能使用量化训练。
量化仅支持 3080、A100 和 TPU。

**Comment by neverstoplearn** [comment]
> Titan X 不能使用量化训练。 量化仅支持 3080、A100 和 TPU。

好的 谢谢

**Comment by NLPAN** [comment]
@AttentionAllUNeed T4好像也不行
