### ISSUE TITLE
单卡设置验证集相关参数能跑，多卡时会报错

### ISSUE THREAD

**Issue by ZR-Huang** [hiyouga/ChatGLM-Efficient-Tuning#163]
参考项目中的文档进行微调，文档地址：https://github.com/hiyouga/ChatGLM-Efficient-Tuning/blob/main/examples/covid_doctor.md

在第三章节，对于模型进行SFT时，参考使用了文档中所提供的训练命令，下面提供的是我的训练命令
```shell
CUDA_VISIBLE_DEVICES=0 python src/train_sft.py \
    --do_train \
    --dataset HTTP_zh_2600 \
    --finetuning_type lora \
    --output_dir output/2600_sft_LoRA \
    --overwrite_cache \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 8 \
    --max_source_length 1024 \
    --max_target_length 512 \
    --lr_scheduler_type cosine \
    --logging_steps  10\
    --save_steps 50 \
    --learning_rate 3e-5 \
    --num_train_epochs 5.0 \
    --dev_ratio 0.1 \
    --evaluation_strategy steps \
    --load_best_model_at_end \
    --plot_loss \
    --fp16
```

在单卡的情况是可以正常训练和验证的。

然后，我用accelerate config进行了相关的配置之后，用accelerate launch修改成单机多卡的模式
```shell
accelerate launch src/train_sft.py \
    --do_train \
    --dataset HTTP_zh_2600 \
    --finetuning_type lora \
    --output_dir output/2600_sft_LoRA \
    --overwrite_cache \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 8 \
    --max_source_length 1024 \
    --max_target_length 512 \
    --lr_scheduler_type cosine \
    --logging_steps  10\
    --save_steps 50 \
    --learning_rate 3e-5 \
    --num_train_epochs 5.0 \
    --dev_ratio 0.1 \
    --evaluation_strategy steps \
    --load_best_model_at_end \
    --plot_loss \
    --fp16
```

模型在训练的过程是正常的，但是在验证过程中会产生异常，下面是对应的日志内容：
```shell
[INFO|trainer.py:1777] 2023-06-15 08:28:26,280 >> ***** Running training *****
[INFO|trainer.py:1778] 2023-06-15 08:28:26,280 >>   Num examples = 2,359
[INFO|trainer.py:1779] 2023-06-15 08:28:26,280 >>   Num Epochs = 5
[INFO|trainer.py:1780] 2023-06-15 08:28:26,280 >>   Instantaneous batch size per device = 4
[INFO|trainer.py:1781] 2023-06-15 08:28:26,280 >>   Total train batch size (w. parallel, distributed & accumulation) = 64
[INFO|trainer.py:1782] 2023-06-15 08:28:26,280 >>   Gradient Accumulation steps = 8
[INFO|trainer.py:1783] 2023-06-15 08:28:26,280 >>   Total optimization steps = 180
[INFO|trainer.py:1784] 2023-06-15 08:28:26,282 >>   Number of trainable parameters = 3,670,016
  1%|▋                                                                                                                     | 1/180 [00:11<35:39, 11.96s/it]06/15/2023 08:28:38 - INFO - torch.nn.parallel.distributed - Reducer buckets have been rebuilt in this iteration.
06/15/2023 08:28:38 - INFO - torch.nn.parallel.distributed - Reducer buckets have been rebuilt in this iteration.
{'loss': 2.0054, 'learning_rate': 2.977211629518312e-05, 'epoch': 0.27}
  6%|██████▌                                                                                                              | 10/180 [01:37<26:28,  9.35s/it][INFO|trainer.py:3190] 2023-06-15 08:30:04,409 >> ***** Running Evaluation *****
[INFO|trainer.py:3192] 2023-06-15 08:30:04,409 >>   Num examples = 263
[INFO|trainer.py:3195] 2023-06-15 08:30:04,409 >>   Batch size = 4
Traceback (most recent call last):
  File "/home/hzr/ChatGLM-Efficient-Tuning/src/train_sft.py", line 100, in <module>
Traceback (most recent call last):
  File "/home/hzr/ChatGLM-Efficient-Tuning/src/train_sft.py", line 100, in <module>
    main()
  File "/home/hzr/ChatGLM-Efficient-Tuning/src/train_sft.py", line 68, in main
    train_result = trainer.train()
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/transformers/trainer.py", line 1645, in train
    main()
  File "/home/hzr/ChatGLM-Efficient-Tuning/src/train_sft.py", line 68, in main
    train_result = trainer.train()
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/transformers/trainer.py", line 2011, in _inner_training_loop
    return inner_training_loop(
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/transformers/trainer.py", line 2011, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/transformers/trainer.py", line 2312, in _maybe_log_save_evaluate
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/transformers/trainer.py", line 2312, in _maybe_log_save_evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/transformers/trainer_seq2seq.py", line 159, in evaluate
    return super().evaluate(eval_dataset, ignore_keys=ignore_keys, metric_key_prefix=metric_key_prefix)
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/transformers/trainer.py", line 3043, in evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/transformers/trainer_seq2seq.py", line 159, in evaluate
    return super().evaluate(eval_dataset, ignore_keys=ignore_keys, metric_key_prefix=metric_key_prefix)
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/transformers/trainer.py", line 3043, in evaluate
    output = eval_loop(
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/transformers/trainer.py", line 3235, in evaluation_loop
    output = eval_loop(
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/transformers/trainer.py", line 3235, in evaluation_loop
    loss, logits, labels = self.prediction_step(model, inputs, prediction_loss_only, ignore_keys=ignore_keys)
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/transformers/trainer_seq2seq.py", line 247, in prediction_step
    return super().prediction_step(
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/transformers/trainer.py", line 3493, in prediction_step
    loss, logits, labels = self.prediction_step(model, inputs, prediction_loss_only, ignore_keys=ignore_keys)
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/transformers/trainer_seq2seq.py", line 247, in prediction_step
    return super().prediction_step(
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/transformers/trainer.py", line 3493, in prediction_step
    loss, outputs = self.compute_loss(model, inputs, return_outputs=True)
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/transformers/trainer.py", line 2775, in compute_loss
    loss, outputs = self.compute_loss(model, inputs, return_outputs=True)
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/transformers/trainer.py", line 2775, in compute_loss
    outputs = model(**inputs)
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    outputs = model(**inputs)
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/peft/peft_model.py", line 707, in forward
    return forward_call(*args, **kwargs)
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/peft/peft_model.py", line 707, in forward
    return self.base_model(
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return self.base_model(
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hzr/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/a8ede826cf1b62bd3c78bdfb3625c7c5d2048fbd/modeling_chatglm.py", line 1190, in forward
    return forward_call(*args, **kwargs)
  File "/home/hzr/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/a8ede826cf1b62bd3c78bdfb3625c7c5d2048fbd/modeling_chatglm.py", line 1190, in forward
    transformer_outputs = self.transformer(
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    transformer_outputs = self.transformer(
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hzr/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/a8ede826cf1b62bd3c78bdfb3625c7c5d2048fbd/modeling_chatglm.py", line 996, in forward
    return forward_call(*args, **kwargs)
  File "/home/hzr/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/a8ede826cf1b62bd3c78bdfb3625c7c5d2048fbd/modeling_chatglm.py", line 996, in forward
    layer_ret = layer(
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    layer_ret = layer(
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hzr/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/a8ede826cf1b62bd3c78bdfb3625c7c5d2048fbd/modeling_chatglm.py", line 624, in forward
    attention_input = self.input_layernorm(hidden_states)
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hzr/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/a8ede826cf1b62bd3c78bdfb3625c7c5d2048fbd/modeling_chatglm.py", line 624, in forward
    attention_input = self.input_layernorm(hidden_states)
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/torch/nn/modules/normalization.py", line 190, in forward
    return F.layer_norm(
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/torch/nn/functional.py", line 2515, in layer_norm
    return forward_call(*args, **kwargs)
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/torch/nn/modules/normalization.py", line 190, in forward
    return F.layer_norm(
  File "/home/hzr/.conda/envs/GLM/lib/python3.10/site-packages/torch/nn/functional.py", line 2515, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: expected scalar type Half but found Float
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: expected scalar type Half but found Float
```

**Comment by Y-L-LIU** [comment]
类型不匹配 用with torch.autocast:跑相关的推理代码

**Comment by yifan-chen-2020** [comment]
> 类型不匹配 用with torch.autocast:跑相关的推理代码
尝试了下载train()时候加入autocast，loss不会下降，一直在2.x，如果不加入则多卡不能跑evaluation，这个问题是怎么回事？
`
with torch.autocast("cuda"):        
        train_result = trainer.train()
        trainer.log_metrics("train", train_result.metrics)
        trainer.save_metrics("train", train_result.metrics)
        trainer.save_state()
        trainer.save_model()
        if trainer.is_world_process_zero() and model_args.plot_loss:
            plot_loss(training_args.output_dir, keys=["loss", "eval_loss"])`
