### ISSUE TITLE
glm2 lora量化4训练后推理报错

### ISSUE THREAD

**Issue by songbaiTalk** [hiyouga/ChatGLM-Efficient-Tuning#182]
训练：
CUDA_VISIBLE_DEVICES=0 python src/train_sft.py \
    --do_train \
    --dataset news \
    --finetuning_type lora \
    --lora_rank 8 \
    --quantization_bit 4 \
    --output_dir news_sft_checkpoint \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 8 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 100 \
    --learning_rate 5e-5 \
    --num_train_epochs 3.0 \
    --fp16 \
    --use_v2

推理：
CUDA_VISIBLE_DEVICES=0 python src/train_sft.py \
    --do_predict \
    --dataset news \
    --quantization_bit 4 \
    --checkpoint_dir news_sft_checkpoint \
    --output_dir news_one_level \
    --per_device_eval_batch_size 2 \
    --max_samples 5 \
    --predict_with_generate

报错：

Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/ChatGLM-Efficient-Tuning/src/train_sft.py", line 100, in <module>
    main()
  File "/home/ec2-user/SageMaker/ChatGLM-Efficient-Tuning/src/train_sft.py", line 86, in main
    predict_results = trainer.predict(dataset, metric_key_prefix="predict", **gen_kwargs)
  File "/home/ec2-user/SageMaker/conda/chatglm_etuning/lib/python3.10/site-packages/transformers/trainer_seq2seq.py", line 216, in predict
    return super().predict(test_dataset, ignore_keys=ignore_keys, metric_key_prefix=metric_key_prefix)
  File "/home/ec2-user/SageMaker/conda/chatglm_etuning/lib/python3.10/site-packages/transformers/trainer.py", line 3129, in predict
    output = eval_loop(
  File "/home/ec2-user/SageMaker/conda/chatglm_etuning/lib/python3.10/site-packages/transformers/trainer.py", line 3235, in evaluation_loop
    for step, inputs in enumerate(dataloader):
  File "/home/ec2-user/SageMaker/conda/chatglm_etuning/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/ec2-user/SageMaker/conda/chatglm_etuning/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/ec2-user/SageMaker/conda/chatglm_etuning/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/home/ec2-user/SageMaker/ChatGLM-Efficient-Tuning/src/utils/data_collator.py", line 123, in __call__
    batch["attention_mask"] = self.get_attention_masks(input_ids, device=input_ids.device)
  File "/home/ec2-user/SageMaker/ChatGLM-Efficient-Tuning/src/utils/data_collator.py", line 45, in get_attention_masks_v1
    attention_mask[i, :, :(seq == self.tokenizer.bos_token_id).nonzero()[0].item()] = 1 # context
AttributeError: 'bool' object has no attribute 'nonzero'

**Comment by hiyouga** [comment]
do_eval 时候也需要 use_v2

**Comment by hiyouga** [comment]
已修复。
