### ISSUE TITLE
[BUG]ChatGLM2-6B模型PPO阶段报错

### ISSUE THREAD

**Issue by Ch4osMy7h** [hiyouga/ChatGLM-Efficient-Tuning#192]
在process_data时候，PPO阶段用的是preprocess_evaluation_dataset，tokenize的时候是没有加上eos_token。
```
Detail:
Traceback (most recent call last):
File "./src/train_ppo.py", line 86, in <module>
main()
File "./src/train_ppo.py", line 73, in main
ppo_trainer.ppo_train(max_target_length=data_args.max_target_length)
File "./src/utils/ppo.py", line 158, in ppo_train
stats = self.step(queries, responses, rewards)
File "/opt/conda/envs/python3.8.13/lib/python3.8/contextlib.py", line 75, in inner
return func(*args, **kwds)
File "/root/.local/lib/python3.8/site-packages/trl/trainer/ppo_trainer.py", line 614, in step
all_logprobs, _, values, masks = self.batched_forward_pass(self.model, queries, responses, model_inputs)
File "/opt/conda/envs/python3.8.13/lib/python3.8/contextlib.py", line 75, in inner
return func(*args, **kwds)
File "./src/utils/ppo.py", line 251, in batched_forward_pass
start = (input_ids[j] == self.tokenizer.bos_token_id).nonzero()[0].item()
IndexError: index 0 is out of bounds for dimension 0 with size 0
```

**Comment by starphantom666** [comment]
你用ChatGLM2训练奖励模型了么？我怎么使用--use_v2这个参数会报错

**Comment by hiyouga** [comment]
PPO阶段的问题正在修复

**Comment by hiyouga** [comment]
PPO 问题现已修复

**Comment by Ch4osMy7h** [comment]
> PPO 问题现已修复

**Comment by Ch4osMy7h** [comment]
> > PPO 问题现已修复

@hiyouga  PPO 中ChatGLMv2的 self.tokenizer.eos_token_id返回为None，会影响src/utils/ppo.py中的两个位置（可能有其他地方，我这边碰到问题主要是这两个）。
> 
> ```
> Example1: 
> gen_kwargs = {
>             "top_k": 0.0,
>             "top_p": 1.0,
>             "do_sample": True,
>             "pad_token_id": self.tokenizer.pad_token_id,
>             "eos_token_id": self.tokenizer.eos_token_id,
>             "logits_processor": get_logits_processor()
> }
> 
> Example2:
> responses.append(response_tensors.new_empty(2).fill_(self.tokenizer.eos_token_id))
> ```
