### ISSUE TITLE
模型评估报错

### ISSUE THREAD

**Issue by shipengcheng1** [hiyouga/ChatGLM-Efficient-Tuning#214]
这里根据如下命令训练成功并保存：accelerate launch src/train_sft.py --do_train --dataset adgen_train --finetuning_type lora --output_dir path_to_sft_checkpoint --per_device_train_batch_size 2 --gradient_accumulation_steps 4 --lr_scheduler_type cosine --logging_steps 290 --save_steps 290 --learning_rate 5e-5 --num_train_epochs 50 --fp16 --use_v2 --model_name_or_path THUDM/chatglm2-6b --quantization_bit 4。
   然后对模型进行评估，命令如下：CUDA_VISIBLE_DEVICES=1 python src/train_sft.py --do_eval  --dataset adgen_dev --checkpoint_dir checkpoint --output_dir adgen_results --per_device_eval_batch_size 4 --predict_with_generate --model_name_or_path THUDM/chatglm2-6b --quantization_bit 4 --use_v2
  报错如下：Traceback (most recent call last):
  File "/home/spc/openChat/ChatGLM-Efficient-Tuning-main/src/train_sft.py", line 105, in <module>
    main()
  File "/home/spc/openChat/ChatGLM-Efficient-Tuning-main/src/train_sft.py", line 25, in main
    model, tokenizer = load_pretrained(model_args, finetuning_args, training_args.do_train, stage="sft")
  File "/home/spc/openChat/ChatGLM-Efficient-Tuning-main/src/utils/common.py", line 180, in load_pretrained
    tokenizer = AutoTokenizer.from_pretrained(
  File "/opt/anaconda3/envs/chatglm_etuning/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 719, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.THUDM.chatglm2-6b.5fe53eb2cc9c2405702b36797be17d875acf3baa.configuration_chatglm.ChatGLMConfig'> to build an AutoTokenizer.
Model type should be one of AlbertConfig, AlignConfig, BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BlipConfig, Blip2Config, BloomConfig, BridgeTowerConfig, CamembertConfig, CanineConfig, ChineseCLIPConfig, ClapConfig, CLIPConfig, CLIPSegConfig, CodeGenConfig, ConvBertConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, DebertaConfig, DebertaV2Config, DistilBertConfig, DPRConfig, ElectraConfig, ErnieConfig, ErnieMConfig, EsmConfig, FlaubertConfig, FNetConfig, FSMTConfig, FunnelConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, GPTSanJapaneseConfig, GroupViTConfig, HubertConfig, IBertConfig, JukeboxConfig, LayoutLMConfig, LayoutLMv2Config, LayoutLMv3Config, LEDConfig, LiltConfig, LlamaConfig, LongformerConfig, LongT5Config, LukeConfig, LxmertConfig, M2M100Config, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MgpstrConfig, MobileBertConfig, MPNetConfig, MT5Config, MvpConfig, NezhaConfig, NllbMoeConfig, NystromformerConfig, OneFormerConfig, OpenAIGPTConfig, OPTConfig, OwlViTConfig, PegasusConfig, PegasusXConfig, PerceiverConfig, Pix2StructConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, RagConfig, RealmConfig, ReformerConfig, RemBertConfig, RetriBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2TextConfig, Speech2Text2Config, SpeechT5Config, SplinterConfig, SqueezeBertConfig, SwitchTransformersConfig, T5Config, TapasConfig, TransfoXLConfig, ViltConfig, VisualBertConfig, Wav2Vec2Config, Wav2Vec2ConformerConfig, WhisperConfig, XCLIPConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, YosoConfig.

**Comment by hiyouga** [comment]
原因是 Huggingface 连接不稳定，请下载模型到本地使用。

**Comment by shipengcheng1** [comment]
网络恢复还是报错

命令如下：CUDA_VISIBLE_DEVICES=1 python src/train_sft.py --do_eval  --dataset adg
Traceback (most recent call last):
  File "/home/spc/openChat/ChatGLM-Efficient-Tuning-main/src/train_sft.py", line 105, in <module>
    main()
  File "/home/spc/openChat/ChatGLM-Efficient-Tuning-main/src/train_sft.py", line 83, in main
    metrics = trainer.evaluate(metric_key_prefix="eval", **gen_kwargs)
  File "/opt/anaconda3/envs/chatglm_etuning/lib/python3.10/site-packages/transformers/trainer_seq2seq.py", line 159, in evaluate
    return super().evaluate(eval_dataset, ignore_keys=ignore_keys, metric_key_prefix=metric_key_prefix)
  File "/opt/anaconda3/envs/chatglm_etuning/lib/python3.10/site-packages/transformers/trainer.py", line 3053, in evaluate
    output = eval_loop(
  File "/opt/anaconda3/envs/chatglm_etuning/lib/python3.10/site-packages/transformers/trainer.py", line 3235, in evaluation_loop
    for step, inputs in enumerate(dataloader):
  File "/opt/anaconda3/envs/chatglm_etuning/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/opt/anaconda3/envs/chatglm_etuning/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/anaconda3/envs/chatglm_etuning/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/home/spc/openChat/ChatGLM-Efficient-Tuning-main/src/utils/data_collator.py", line 144, in __call__
    batch["attention_mask"] = self.get_attention_masks(input_ids, device=input_ids.device)
  File "/home/spc/openChat/ChatGLM-Efficient-Tuning-main/src/utils/data_collator.py", line 46, in get_attention_masks_v1
    attention_mask[i, :, :(seq == self.tokenizer.bos_token_id).nonzero()[0].item()] = 1 # context
AttributeError: 'bool' object has no attribute 'nonzero'
en_dev --checkpoint_dir checkpoint --output_dir adgen_results --per_device_eval_batch_size 4 --predict_with_generate --model_name_or_path THUDM/chatglm2-6b --quantization_bit 4

报错：

**Comment by shipengcheng1** [comment]
网络恢复还是报错
命令如下：CUDA_VISIBLE_DEVICES=1 python src/train_sft.py --do_eval  --dataset adgen_dev --checkpoint_dir checkpoint --output_dir adgen_results --per_device_eval_batch_size 4 --predict_with_generate --model_name_or_path THUDM/chatglm2-6b --quantization_bit 4


报错如下：

[INFO|trainer.py:3200] 2023-06-29 19:06:32,865 >> ***** Running Evaluation *****
[INFO|trainer.py:3202] 2023-06-29 19:06:32,865 >>   Num examples = 703
[INFO|trainer.py:3205] 2023-06-29 19:06:32,865 >>   Batch size = 4
Traceback (most recent call last):
  File "/home/spc/openChat/ChatGLM-Efficient-Tuning-main/src/train_sft.py", line 105, in <module>
    main()
  File "/home/spc/openChat/ChatGLM-Efficient-Tuning-main/src/train_sft.py", line 83, in main
    metrics = trainer.evaluate(metric_key_prefix="eval", **gen_kwargs)
  File "/opt/anaconda3/envs/chatglm_etuning/lib/python3.10/site-packages/transformers/trainer_seq2seq.py", line 159, in evaluate
    return super().evaluate(eval_dataset, ignore_keys=ignore_keys, metric_key_prefix=metric_key_prefix)
  File "/opt/anaconda3/envs/chatglm_etuning/lib/python3.10/site-packages/transformers/trainer.py", line 3053, in evaluate
    output = eval_loop(
  File "/opt/anaconda3/envs/chatglm_etuning/lib/python3.10/site-packages/transformers/trainer.py", line 3235, in evaluation_loop
    for step, inputs in enumerate(dataloader):
  File "/opt/anaconda3/envs/chatglm_etuning/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/opt/anaconda3/envs/chatglm_etuning/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/anaconda3/envs/chatglm_etuning/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/home/spc/openChat/ChatGLM-Efficient-Tuning-main/src/utils/data_collator.py", line 144, in __call__
    batch["attention_mask"] = self.get_attention_masks(input_ids, device=input_ids.device)
  File "/home/spc/openChat/ChatGLM-Efficient-Tuning-main/src/utils/data_collator.py", line 46, in get_attention_masks_v1
    attention_mask[i, :, :(seq == self.tokenizer.bos_token_id).nonzero()[0].item()] = 1 # context
AttributeError: 'bool' object has no attribute 'nonzero'

**Comment by hiyouga** [comment]
--use_v2 参数去哪里了

**Comment by shipengcheng1** [comment]
加了--use_v2还是报错：
Generation config file not found, using a generation config created from the model config.
Traceback (most recent call last):
  File "/home/spc/openChat/ChatGLM-Efficient-Tuning-main/src/train_sft.py", line 105, in <module>
    main()
  File "/home/spc/openChat/ChatGLM-Efficient-Tuning-main/src/train_sft.py", line 25, in main
    model, tokenizer = load_pretrained(model_args, finetuning_args, training_args.do_train, stage="sft")
  File "/home/spc/openChat/ChatGLM-Efficient-Tuning-main/src/utils/common.py", line 235, in load_pretrained
    tokenizer.eos_token = "</s>"
AttributeError: can't set attribute 'eos_token'

**Comment by hiyouga** [comment]
更新代码
