### ISSUE TITLE
请问在多卡运行文件fine_tuning_chatglm6b.py时报错是什么原因呢？

### ISSUE THREAD

**Issue by LebronJames0423** [hiyouga/ChatGLM-Efficient-Tuning#22]
alpaca_dataset.py", line 28, in __init__
    self.eop = tokenizer.eop_token_id
AttributeError: 'ChatGLMTokenizer' object has no attribute 'eop_token_id'

**Comment by hiyouga** [comment]
模型版本过旧，请更新本地模型文件。
https://github.com/hiyouga/ChatGLM-Efficient-Tuning/wiki/常见报错信息汇总

**Comment by LebronJames0423** [comment]
好的，但我是刚刚拉的新工程啊，模型好像是最新的，怎么更新模型文件呢？我是拉的远程的代码AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)

**Comment by hiyouga** [comment]
> 好的，但我是刚刚拉的新工程啊，模型好像是最新的，怎么更新模型文件呢？我是拉的远程的代码AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)

麻烦截取一下完整的报错信息。

**Comment by LebronJames0423** [comment]
![image](https://user-images.githubusercontent.com/33833521/233842334-b166d98b-490f-4e89-b536-e4b4e094035a.png)
![image](https://user-images.githubusercontent.com/33833521/233842376-9c37002a-fced-440c-b869-936574db9fa9.png)

**Comment by LebronJames0423** [comment]
加了ignore_mismatched_sizes=True这个之后
![image](https://user-images.githubusercontent.com/33833521/233842454-9b4798d8-c32d-47fd-b29a-d832f7a27c25.png)

![image](https://user-images.githubusercontent.com/33833521/233842443-ee410b16-41c8-4765-83bd-68151d53703d.png)

**Comment by hiyouga** [comment]
> 加了ignore_mismatched_sizes=True这个之后

我不太明白 `fine_tuning_chatglm6b.py` 的逻辑，这属于该项目框架外的内容。

**Comment by LebronJames0423** [comment]
哦这个是另一个问题，我给看错了，不好意思。请问下这里的多GPU分布式环境如何设置可以提供一个例子吗？之前没用过accelerate，我是准备在同一台机器上用多个GPU来跑，谢谢
![image](https://user-images.githubusercontent.com/33833521/233887449-404ff54f-ec4b-4811-b841-2744184520db.png)

**Comment by hiyouga** [comment]
> 哦这个是另一个问题，我给看错了，不好意思。请问下这里的多GPU分布式环境如何设置可以提供一个例子吗？之前没用过accelerate，我是准备在同一台机器上用多个GPU来跑，谢谢

增加了一个案例教程：https://github.com/hiyouga/ChatGLM-Efficient-Tuning/blob/main/examples/ads_generation.md

**Comment by LebronJames0423** [comment]
好的谢谢

**Comment by yudonggithub** [comment]
我也是，模型加载部分后，就报错
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 1 (pid: 59241) of binary: /root/anaconda3/envs/chatglm/bin/python
Traceback (most recent call last):
  File "/root/anaconda3/envs/chatglm/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/accelerate/commands/launch.py", line 970, in launch_command
    multi_gpu_launcher(args)
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
