### ISSUE TITLE
用 accelerate 多模式微调模型，多卡使用异常。

### ISSUE THREAD

**Issue by online2311** [hiyouga/ChatGLM-Efficient-Tuning#231]
用 accelerate 普通的多卡模式可以微调模型，但是采用 deepspeed 与 dsdp 就都不行。

微调配置
```
accelerate launch --config_file accelerate_config.yaml src/train_sft.py \
    --do_train \
    --dataset self_cognition \
    --finetuning_type lora \
    --output_dir checkpoint \
    --overwrite_cache \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --gradient_accumulation_steps 2 \
    --max_source_length 512 \
    --max_target_length 512 \
    --max_grad_norm 0.5 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 1e-3 \
    --num_train_epochs 32.0 \
    --plot_loss \
    --fp16 \
    --model_name_or_path /app/models/THUDM_chatglm2-6b \
    --ddp_find_unused_parameters False \
    --use_v2
```
```
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```
---
# deepspeed
配置如下：
```
compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_accumulation_steps: 2
  gradient_clipping: 0.5
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: false
  zero_stage: 2
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```
错误提示：
```
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 4537 closing signal SIGTERM
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/agent/server/api.py", line 723, in run
    result = self._invoke_run(role)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/agent/server/api.py", line 864, in _invoke_run
    time.sleep(monitor_interval)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/api.py", line 62, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 4484 got signal: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 926, in launch_command
    deepspeed_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 671, in deepspeed_launcher
    distrib_run.run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 241, in launch_agent
    result = agent.run()
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/agent/server/api.py", line 730, in run
    self._shutdown(e.sigval)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/agent/server/local_elastic_agent.py", line 289, in _shutdown
    self._pcontext.close(death_sig)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/api.py", line 331, in close
    self._close(death_sig=death_sig, timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/api.py", line 708, in _close
    handler.proc.wait(time_to_wait)
  File "/usr/lib/python3.10/subprocess.py", line 1207, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1935, in _wait
    time.sleep(delay)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/api.py", line 62, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 4484 got signal: 2
```
----
#  fsdp
配置如下：
```
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: FSDP
downcast_bf16: 'no'
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch_policy: BACKWARD_PRE
  fsdp_offload_params: false
  fsdp_sharding_strategy: 1
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_transformer_layer_cls_to_wrap: GPT2Block
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 2
use_cpu: false
```
错误提示 
```
07/02/2023 03:54:35 - WARNING - accelerate.accelerator - FSDP Warning: When using FSDP, it is efficient and recommended to call prepare for the model before creating the optimizer
Traceback (most recent call last):
  File "/app/src/train_sft.py", line 105, in <module>
    main()
  File "/app/src/train_sft.py", line 73, in main
    train_result = trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1756, in _inner_training_loop
    model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1182, in prepare
    result = tuple(
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1183, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1022, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1284, in prepare_model
    self.state.fsdp_plugin.set_auto_wrap_policy(model)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/dataclasses.py", line 863, in set_auto_wrap_policy
    raise Exception("Could not find the transformer layer class to wrap in the model.")
Exception: Could not find the transformer layer class to wrap in the model.
Traceback (most recent call last):
  File "/app/src/train_sft.py", line 105, in <module>
    main()
  File "/app/src/train_sft.py", line 73, in main
    train_result = trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1756, in _inner_training_loop
    model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1182, in prepare
    result = tuple(
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1183, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1022, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1284, in prepare_model
    self.state.fsdp_plugin.set_auto_wrap_policy(model)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/dataclasses.py", line 863, in set_auto_wrap_policy
    raise Exception("Could not find the transformer layer class to wrap in the model.")
Exception: Could not find the transformer layer class to wrap in the model.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 4663) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 928, in launch_command
    multi_gpu_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 627, in multi_gpu_launcher
    distrib_run.run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
src/train_sft.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-07-02_03:54:37
  host      : nodecloud-ai-server
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 4664)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-02_03:54:37
  host      : nodecloud-ai-server
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 4663)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by ArtificialZeng** [comment]
File "D:\ai_zeng\ChatGLM-Efficient-Tuning\src\train_sft.py", line 28, in main
    model_args, data_args, training_args, finetuning_args = prepare_args(stage="sft")
model_args, data_args, training_args, finetuning_args = prepare_args(stage="sft")  File "D:\ai_zeng\ChatGLM-Efficient-Tuning\src\utils\common.py", line 295, in prepare_args

      File "D:\ai_zeng\ChatGLM-Efficient-Tuning\src\utils\common.py", line 295, in prepare_args
model_args, data_args, training_args, finetuning_args = parser.parse_args_into_dataclasses()
      File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\transformers\hf_argparser.py", line 346, in parse_args_into_dataclasses
model_args, data_args, training_args, finetuning_args = parser.parse_args_into_dataclasses()
obj = dtype(**inputs)  File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\transformers\hf_argparser.py", line 346, in parse_args_into_dataclasses

      File "<string>", line 116, in __init__
obj = dtype(**inputs)
  File "<string>", line 116, in __init__
  File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\transformers\training_args.py", line 1340, in __post_init__  File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\transformers\training_args.py", line 1340, in __post_init__        and (self.device.type != "cuda")and (self.device.type != "cuda")

  File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\transformers\training_args.py", line 1764, in device
  File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\transformers\training_args.py", line 1764, in device
    return self._setup_devices
return self._setup_devices  File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\transformers\utils\generic.py", line 54, in __get__

      File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\transformers\utils\generic.py", line 54, in __get__
cached = self.fget(obj)    cached = self.fget(obj)

  File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\transformers\training_args.py", line 1695, in _setup_devices
  File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\transformers\training_args.py", line 1695, in _setup_devices
        self.distributed_state = PartialState(backend=self.ddp_backend)self.distributed_state = PartialState(backend=self.ddp_backend)

  File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\accelerate\state.py", line 197, in __init__
  File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\accelerate\state.py", line 197, in __init__
        torch.cuda.set_device(self.device)torch.cuda.set_device(self.device)

  File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\torch\cuda\__init__.py", line 350, in set_device
  File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\torch\cuda\__init__.py", line 350, in set_device
        torch._C._cuda_setDevice(device)torch._C._cuda_setDevice(device)

AttributeErrorAttributeError: module 'torch._C' has no attribute '_cuda_setDevice': module 'torch._C' has no attribute '_cuda_setDevice'

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 26208) of binary: D:\ProgramData\anaconda3\envs\py10\python.exe
Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\py10\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\ProgramData\anaconda3\envs\py10\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\anaconda3\envs\py10\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\accelerate\commands\launch.py", line 928, in launch_command    multi_gpu_launcher(args)
  File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\accelerate\commands\launch.py", line 627, in multi_gpu_launcher
    distrib_run.run(args)
  File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\torch\distributed\run.py", line 785, in run
    elastic_launch(
  File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\torch\distributed\launcher\api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "D:\ProgramData\anaconda3\envs\py10\lib\site-packages\torch\distributed\launcher\api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
src/train_sft.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-07-03_23:45:01
  host      : XTZJ-20210729YS
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 26228)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-03_23:45:01
  host      : XTZJ-20210729YS
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 26208)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
