### ISSUE TITLE
--finetuning_type freeze  错误

### ISSUE THREAD

**Issue by qxde01** [hiyouga/ChatGLM-Efficient-Tuning#241]
使用`--finetuning_type freeze`时，如果加载上次训练的结果 `--checkpoint_dir output10/checkpoint-900`继续训练
出现下面的错误
```
 File "src/train_sft.py", line 106, in <module>
    main()
  File "src/train_sft.py", line 25, in main
    model, tokenizer = load_pretrained(model_args, finetuning_args, training_args.do_train, stage="sft")
  File "/root/autodl-tmp/ChatGLM-Efficient-Tuning/src/utils/common.py", line 236, in load_pretrained
    model = init_adapter(model, model_args, finetuning_args, is_trainable)
  File "/root/autodl-tmp/ChatGLM-Efficient-Tuning/src/utils/common.py", line 96, in init_adapter
    assert load_trainable_params(model, model_args.checkpoint_dir[0]), "Model checkpoint is not correctly loaded."
  File "/root/autodl-tmp/ChatGLM-Efficient-Tuning/src/utils/other.py", line 136, in load_trainable_params
    model.load_state_dict(model_state_dict, strict=False) # skip missing keys
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ChatGLMForConditionalGeneration:
        size mismatch for transformer.encoder.layers.27.mlp.dense_h_to_4h.weight: copying a param with shape torch.Size([27392, 4096]) from checkpoint, the shape in current model is torch.Size([56098816, 1]).
        size mismatch for transformer.encoder.layers.27.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 13696]) from checkpoint, the shape in current model is torch.Size([28049408, 1]).
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 38756) of binary: /root/miniconda3/bin/python3
Traceback (most recent call last):
  File "/root/miniconda3/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1+cu118', 'console_scripts', 'torchrun')())
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

```

**Comment by HaKLMTT** [comment]
加这个参数了吗？
--model_name_or_path "path/chatglm2-6b"\

**Comment by qxde01** [comment]
@hiyouga 加了，8X4090上测试的
