### ISSUE TITLE
多卡训练报错

### ISSUE THREAD

**Issue by songbaiTalk** [hiyouga/ChatGLM-Efficient-Tuning#242]
sft.sh
accelerate launch --config_file accelerate_config.yaml src/train_sft.py \
    --do_train \
    --dataset self_cognition \
    --finetuning_type lora \
    --output_dir checkpoint \
    --overwrite_cache \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --gradient_accumulation_steps 2 \
    --max_source_length 512 \
    --max_target_length 512 \
    --max_grad_norm 0.5 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 1e-3 \
    --num_train_epochs 32.0 \
    --plot_loss \
    --fp16 \
    --model_name_or_path THUDM/chatglm2-6b \
    --ddp_find_unused_parameters False \
    --use_v2
accelerate_config.yaml
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

报错：

Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/ChatGLM-Efficient-Tuning/src/train_sft.py", line 106, in <module>
    main()
  File "/home/ec2-user/SageMaker/ChatGLM-Efficient-Tuning/src/train_sft.py", line 74, in main
    train_result = trainer.train()
  File "/home/ec2-user/SageMaker/conda/chatglm_etuning/lib/python3.10/site-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/home/ec2-user/SageMaker/conda/chatglm_etuning/lib/python3.10/site-packages/transformers/trainer.py", line 1938, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/ec2-user/SageMaker/conda/chatglm_etuning/lib/python3.10/site-packages/transformers/trainer.py", line 2759, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/ec2-user/SageMaker/conda/chatglm_etuning/lib/python3.10/site-packages/transformers/trainer.py", line 2784, in compute_loss
    outputs = model(**inputs)
  File "/home/ec2-user/SageMaker/conda/chatglm_etuning/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ec2-user/SageMaker/conda/chatglm_etuning/lib/python3.10/site-packages/accelerate/utils/operations.py", line 553, in forward
    return model_forward(*args, **kwargs)
  File "/home/ec2-user/SageMaker/conda/chatglm_etuning/lib/python3.10/site-packages/accelerate/utils/operations.py", line 541, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/ec2-user/SageMaker/conda/chatglm_etuning/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/ec2-user/SageMaker/conda/chatglm_etuning/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1139, in forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).

**Comment by hiyouga** [comment]
单卡能正常运行吗？

**Comment by hiyouga** [comment]
提供一下 pytorch 和 accelerate 版本

**Comment by songbaiTalk** [comment]
> 提供一下 pytorch 和 accelerate 版本

torch：2.0.1+cu117
accelerate：0.20.3

**Comment by CodeWang-Ay** [comment]
我也是这个问题， 在A100上可以单机多卡 但是在3090上不行 请问解决了吗

**Comment by neptunear** [comment]
> 

你是3090 24G吗, 请问你解决了吗

**Comment by FrankWhh** [comment]
奇怪，我碰到单卡训练正常，多卡就发散的问题
