### ISSUE TITLE
ChatGLM-6B Lora int8 量化 训练出现类型不匹配问题 求大佬们点拨

### ISSUE THREAD

**Issue by Zaaachary** [hiyouga/ChatGLM-Efficient-Tuning#260]
运行的 sh 文件内容
```
CUDA_VISIBLE_DEVICES=0 python src/train_sft.py \
    --model_name_or_path /SISDC_GPFS/Home_SE/hy-suda/pre-train_model/chatglm-6b \
    --use_v2 False \
    --quantization_bit 8 \
    --do_train \
    --dataset alpaca_gpt4_en \
    --finetuning_type lora \
    --output_dir /SISDC_GPFS/Home_SE/hy-suda/zfli/Models/Finetuned_model/ChatGLM \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 5e-5 \
    --num_train_epochs 3.0 \
    --fp16
```

fp16 开启， quantization_bit  8， model_name_or_path 是未经量化的模型。

目前开始训练，在反向传播的时候报错。、
报错信息如下：
```
[INFO|trainer.py:407] 2023-07-06 22:09:13,494 >> The model is loaded in 8-bit precision. To train this model you need to add additional modules inside the model such as adapters using `peft` library and freeze the model weights. Please check  the examples in https://github.com/huggingface/peft for more details.
[INFO|trainer.py:1786] 2023-07-06 22:09:13,640 >> ***** Running training *****
[INFO|trainer.py:1787] 2023-07-06 22:09:13,640 >>   Num examples = 52,002
[INFO|trainer.py:1788] 2023-07-06 22:09:13,640 >>   Num Epochs = 3
[INFO|trainer.py:1789] 2023-07-06 22:09:13,640 >>   Instantaneous batch size per device = 4
[INFO|trainer.py:1790] 2023-07-06 22:09:13,640 >>   Total train batch size (w. parallel, distributed & accumulation) = 16
[INFO|trainer.py:1791] 2023-07-06 22:09:13,640 >>   Gradient Accumulation steps = 4
[INFO|trainer.py:1792] 2023-07-06 22:09:13,640 >>   Total optimization steps = 9,750
[INFO|trainer.py:1793] 2023-07-06 22:09:13,641 >>   Number of trainable parameters = 3,670,016
  0%|                                                                 | 0/9750 [00:00<?, ?it/s]/SISDC_GPFS/Home_SE/hy-suda/ENTER/envs/zfli_LLM/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py:321: UserWarning: MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
Traceback (most recent call last):
  File "/SISDC_GPFS/Home_SE/hy-suda/zfli/CODE/LLM/ChatGLM-Efficient-Tuning/src/train_sft.py", line 105, in <module>
    main()
  File "/SISDC_GPFS/Home_SE/hy-suda/zfli/CODE/LLM/ChatGLM-Efficient-Tuning/src/train_sft.py", line 73, in main
    train_result = trainer.train()
  File "/SISDC_GPFS/Home_SE/hy-suda/ENTER/envs/zfli_LLM/lib/python3.10/site-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/SISDC_GPFS/Home_SE/hy-suda/ENTER/envs/zfli_LLM/lib/python3.10/site-packages/transformers/trainer.py", line 1938, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/SISDC_GPFS/Home_SE/hy-suda/ENTER/envs/zfli_LLM/lib/python3.10/site-packages/transformers/trainer.py", line 2770, in training_step
    self.accelerator.backward(loss)
  File "/SISDC_GPFS/Home_SE/hy-suda/ENTER/envs/zfli_LLM/lib/python3.10/site-packages/accelerate/accelerator.py", line 1819, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "/SISDC_GPFS/Home_SE/hy-suda/ENTER/envs/zfli_LLM/lib/python3.10/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/SISDC_GPFS/Home_SE/hy-suda/ENTER/envs/zfli_LLM/lib/python3.10/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/SISDC_GPFS/Home_SE/hy-suda/ENTER/envs/zfli_LLM/lib/python3.10/site-packages/torch/autograd/function.py", line 267, in apply
    return user_fn(self, *args)
  File "/SISDC_GPFS/Home_SE/hy-suda/ENTER/envs/zfli_LLM/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 157, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/SISDC_GPFS/Home_SE/hy-suda/ENTER/envs/zfli_LLM/lib/python3.10/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/SISDC_GPFS/Home_SE/hy-suda/ENTER/envs/zfli_LLM/lib/python3.10/site-packages/torch/autograd/function.py", line 267, in apply
    return user_fn(self, *args)
  File "/SISDC_GPFS/Home_SE/hy-suda/ENTER/envs/zfli_LLM/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 479, in backward
    grad_A = torch.matmul(grad_output, CB).view(ctx.grad_shape).to(ctx.dtype_A)
RuntimeError: expected scalar type Half but found Float
  0%|                                                                 | 0/9750 [00:01<?, ?it/s]
```

**Comment by hiyouga** [comment]
目前仅 3090 以上和 A100 显卡支持量化训练
