### ISSUE TITLE
P-Tuning v2 单卡训练报错，past_key_values.view（）shape is invalid for input of size ...

### ISSUE THREAD

**Issue by 87oo** [hiyouga/ChatGLM-Efficient-Tuning#280]
感谢作者的贡献。用以下命令测试P-Tuning V2的时候，报错如下：

Traceback (most recent call last):
  File "/home/hhh/data/workspace/ChatGLM-Efficient-Tuning/src/train_bash.py", line 21, in <module>
    main()
  File "/home/hhh/data/workspace/ChatGLM-Efficient-Tuning/src/train_bash.py", line 8, in main
    run_sft(model_args, data_args, training_args, finetuning_args)
  File "/home/hhh/data/workspace/ChatGLM-Efficient-Tuning/src/pet/sft/workflow.py", line 72, in run_sft
    train_result = trainer.train()
  File "/home/hhh/anaconda3/envs/chatglm6b-efficient-tuning/lib/python3.9/site-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/home/hhh/anaconda3/envs/chatglm6b-efficient-tuning/lib/python3.9/site-packages/transformers/trainer.py", line 1938, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/hhh/anaconda3/envs/chatglm6b-efficient-tuning/lib/python3.9/site-packages/transformers/trainer.py", line 2759, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/hhh/anaconda3/envs/chatglm6b-efficient-tuning/lib/python3.9/site-packages/transformers/trainer.py", line 2784, in compute_loss
    outputs = model(**inputs)
  File "/home/hhh/anaconda3/envs/chatglm6b-efficient-tuning/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hhh/.cache/huggingface/modules/transformers_modules/chatglm2-6b/modeling_chatglm.py", line 931, in forward
    transformer_outputs = self.transformer(
  File "/home/hhh/anaconda3/envs/chatglm6b-efficient-tuning/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hhh/.cache/huggingface/modules/transformers_modules/chatglm2-6b/modeling_chatglm.py", line 808, in forward
    past_key_values = self.get_prompt(batch_size=batch_size, device=input_ids.device,
  File "/home/hhh/.cache/huggingface/modules/transformers_modules/chatglm2-6b/modeling_chatglm.py", line 771, in get_prompt
    past_key_values = past_key_values.view(
RuntimeError: shape '[2, 128, 56, 2, 128]' is invalid for input of size 58720256

运行命令：

CUDA_VISIBLE_DEVICES=0 python src/train_bash.py \
--stage sft \
--do_train \
--model_name_or_path ../Data_Models/models/chatglm2-6b \
--dataset alpaca_gpt4_zh \
--finetuning_type p_tuning \
--pre_seq_len 128 \
--prefix_projection true \
--output_dir path_to_sft_checkpoint \
--per_device_train_batch_size 2 \
--gradient_accumulation_steps 8 \
--lr_scheduler_type cosine \
--logging_steps 10 \
--save_steps 1000 \
--learning_rate 5e-5 \
--num_train_epochs 3.0 \
--max_source_length 256 \
--max_target_length 256 \
--use_v2 \
--quantization_bit 8 \

期待回复。

**Comment by hiyouga** [comment]
模型文件是最新版本吗？

**Comment by 87oo** [comment]
> 模型文件是最新版本吗？

嗯嗯，多谢指点，现在ok啦。原来模型7 days更新了 modeling_chatglm.py文件。
