### ISSUE TITLE
export_model.py Execute merge using api_demo. py starts. But an error was reported. I need help

### ISSUE THREAD

**Issue by wgq910668** [hiyouga/ChatGLM-Efficient-Tuning#293]
hi, Team, i have som problem. This is saving information

python src/api_demo.py --model_name_or_path /data/project/ChatGLM-Efficient-Tuning/path_to_export --checkpoint_dir  /data/project/ChatGLM-Efficient-Tuning/examples/path_to_sft_checkpoint100
[2023-07-16 09:50:40,930] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Could not locate the tokenization_chatglm.py inside /data/project/ChatGLM-Efficient-Tuning/path_to_export.
Traceback (most recent call last):
  File "/data/project/ChatGLM-Efficient-Tuning/src/api_demo.py", line 12, in <module>
    app = create_app()
  File "/data/project/ChatGLM-Efficient-Tuning/src/glmtuner/api/app.py", line 32, in create_app
    chat_model = ChatModel(*get_infer_args())
  File "/data/project/ChatGLM-Efficient-Tuning/src/glmtuner/chat/stream_chat.py", line 17, in __init__
    self.model, self.tokenizer = load_model_and_tokenizer(model_args, finetuning_args)
  File "/data/project/ChatGLM-Efficient-Tuning/src/glmtuner/tuner/core/loader.py", line 72, in load_model_and_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
  File "/home/fastchat/miniconda3/envs/chatGLM-efficient/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 676, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
  File "/home/fastchat/miniconda3/envs/chatGLM-efficient/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 431, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/home/fastchat/miniconda3/envs/chatGLM-efficient/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 247, in get_cached_module_file
    resolved_module_file = cached_file(
  File "/home/fastchat/miniconda3/envs/chatGLM-efficient/lib/python3.10/site-packages/transformers/utils/hub.py", line 388, in cached_file
    raise EnvironmentError(
OSError: /data/project/ChatGLM-Efficient-Tuning/path_to_export does not appear to have a file named tokenization_chatglm.py. Checkout 'https://huggingface.co//data/project/ChatGLM-Efficient-Tuning/path_to_export/main' for available files.

**Comment by hiyouga** [comment]
Fixed, please update your code with `git push`.
