### ISSUE TITLE
When loading the train_bash.py, an error was reported. 

### ISSUE THREAD

**Issue by canglincuizhu** [hiyouga/ChatGLM-Efficient-Tuning#294]
The details of the error:

Traceback (most recent call last):
  File "src/train_bash.py", line 1, in <module>
    from glmtuner import get_train_args, run_sft, run_rm, run_ppo
  File "./ChatGLM-Efficient-Tuning/src/glmtuner/__init__.py", line 1, in <module>
    from glmtuner.api import create_app
  File "./ChatGLM-Efficient-Tuning/src/glmtuner/api/__init__.py", line 1, in <module>
    from glmtuner.api.app import create_app
  File "./ChatGLM-Efficient-Tuning/src/glmtuner/api/app.py", line 11, in <module>
    from glmtuner.api.protocol import (
  File "./ChatGLM-Efficient-Tuning/src/glmtuner/api/protocol.py", line 21, in <module>
    class ChatMessage(BaseModel):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/usr/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

I don't know why and need some help.

**Comment by hiyouga** [comment]
Please provide the version of `typing` and `pydantic`.

**Comment by canglincuizhu** [comment]
The versions are as follows: typing-inspect is 0.9.0, typing-extensions is 4.7.1, and pydantic is 1.10.7.

**Comment by xiabo0816** [comment]
Same error, Python 3.8.10, `pydantic`==1.10.7,

**Comment by xiabo0816** [comment]
Dependence Installation
```bash
git clone https://github.com/hiyouga/ChatGLM-Efficient-Tuning.git
conda create -n chatglm_etuning python=3.10
conda activate chatglm_etuning
cd ChatGLM-Efficient-Tuning
pip install -r requirements.txt
```
