### ISSUE TITLE
多卡微调报错：RuntimeError: [enforce fail at inline_container.cc:471] . PytorchStreamWriter failed writing file data.pkl: file write failed

### ISSUE THREAD

**Issue by BBBxG** [hiyouga/ChatGLM-Efficient-Tuning#315]
麻烦问一下使用accelerate+deepspeed进行多卡微调时出现以下报错是什么原因呢？
 0%|                                                                                                         | 0/4575 [00:00<?, ?it/s][2023-07-18 14:24:38,015] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 4294967296, reducing to 2147483648
  0%|                                                                                               | 1/4575 [00:03<4:56:55,  3.89s/it][2023-07-18 14:24:40,578] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 2147483648, reducing to 1073741824
  0%|                                                                                               | 2/4575 [00:06<3:57:10,  3.11s/it][2023-07-18 14:24:43,029] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 1073741824, reducing to 536870912
  0%|                                                                                               | 3/4575 [00:08<3:34:07,  2.81s/it][2023-07-18 14:24:45,986] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 536870912, reducing to 268435456
  0%|                                                                                               | 4/4575 [00:11<3:38:29,  2.87s/it][2023-07-18 14:24:49,292] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 268435456, reducing to 134217728
  0%|                                                                                               | 5/4575 [00:15<3:50:27,  3.03s/it][2023-07-18 14:24:52,131] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 134217728, reducing to 67108864
  0%|                                                                                               | 6/4575 [00:18<3:45:35,  2.96s/it][2023-07-18 14:24:55,452] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 67108864, reducing to 33554432
  0%|▏                                                                                              | 7/4575 [00:21<3:54:27,  3.08s/it][2023-07-18 14:24:58,531] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 33554432, reducing to 16777216
  0%|▏                                                                                              | 8/4575 [00:24<3:54:23,  3.08s/it][2023-07-18 14:25:01,503] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 16777216, reducing to 8388608
  0%|▏                                                                                              | 9/4575 [00:27<3:51:46,  3.05s/it][2023-07-18 14:25:04,141] [INFO] [loss_scaler.py:183:update_scale] [deepspeed] OVERFLOW! Rank 0 Skipping step. Attempted loss scale: 8388608, reducing to 4194304
{'loss': 2.6843, 'learning_rate': 5e-05, 'epoch': 0.01}
  0%|▏                                                                                             | 10/4575 [00:33<3:42:09,  2.92s/it]07/18/2023 14:25:07 - INFO - glmtuner.tuner.core.trainer - Saving model checkpoint to lora_checkpoint/checkpoint-10
Traceback (most recent call last):
  File "/noah/bin/anaconda3/envs/chatglm_etuning/lib/python3.10/site-packages/torch/serialization.py", line 441, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/noah/bin/anaconda3/envs/chatglm_etuning/lib/python3.10/site-packages/torch/serialization.py", line 655, in _save
    zip_file.write_record('data.pkl', data_value, len(data_value))
RuntimeError: [enforce fail at inline_container.cc:471] . PytorchStreamWriter failed writing file data.pkl: file write failed

Traceback (most recent call last):
  File "/noah/download/aigc_llm/guobaixiu/ChatGLM-Efficient-Tuning-main/src/train_bash.py", line 21, in <module>
    main()
  File "/noah/download/aigc_llm/guobaixiu/ChatGLM-Efficient-Tuning-main/src/train_bash.py", line 8, in main
    run_sft(model_args, data_args, training_args, finetuning_args)
  File "/noah/download/aigc_llm/guobaixiu/ChatGLM-Efficient-Tuning-main/src/glmtuner/tuner/sft/workflow.py", line 71, in run_sft
    train_result = trainer.train()
  File "/noah/bin/anaconda3/envs/chatglm_etuning/lib/python3.10/site-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/noah/bin/anaconda3/envs/chatglm_etuning/lib/python3.10/site-packages/transformers/trainer.py", line 2020, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/noah/bin/anaconda3/envs/chatglm_etuning/lib/python3.10/site-packages/transformers/trainer.py", line 2332, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/noah/bin/anaconda3/envs/chatglm_etuning/lib/python3.10/site-packages/transformers/trainer.py", line 2389, in _save_checkpoint
    self.save_model(output_dir, _internal_call=True)
  File "/noah/bin/anaconda3/envs/chatglm_etuning/lib/python3.10/site-packages/transformers/trainer.py", line 2863, in save_model
    self._save(output_dir)
  File "/noah/download/aigc_llm/guobaixiu/ChatGLM-Efficient-Tuning-main/src/glmtuner/tuner/core/trainer.py", line 63, in _save
    backbone_model.save_pretrained(output_dir, state_dict=get_state_dict(backbone_model))
  File "/noah/bin/anaconda3/envs/chatglm_etuning/lib/python3.10/site-packages/peft/peft_model.py", line 130, in save_pretrained
    torch.save(output_state_dict, os.path.join(output_dir, WEIGHTS_NAME))
  File "/noah/bin/anaconda3/envs/chatglm_etuning/lib/python3.10/site-packages/torch/serialization.py", line 440, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/noah/bin/anaconda3/envs/chatglm_etuning/lib/python3.10/site-packages/torch/serialization.py", line 291, in __exit__
    self.file_like.write_end_of_file()
RuntimeError: [enforce fail at inline_container.cc:337] . unexpected pos 64 vs 0
  0%|▏                                                                                             | 10/4575 [00:33<4:18:01,  3.39s/it]
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 21093 closing signal SIGTERM

**Comment by YinSonglin1997** [comment]
我也遇到了相似的报错，`RuntimeError: [enforce fail at inline_container.cc:471] . PytorchStreamWriter failed writing file data/31: file write failed`本以为是磁盘满了，结果free -h查了下还有180G空闲，很奇怪。
请问你解决这个问题了吗？
