### ISSUE TITLE
API 报错，chat response 处理有问题

### ISSUE THREAD

**Issue by snachx** [hiyouga/ChatGLM-Efficient-Tuning#317]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/conda/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/opt/conda/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/opt/conda/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/opt/conda/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/workspace/chatglm-efficient-tuning-new/src/glmtuner/api/app.py", line 84, in create_chat_completion
    message=ChatMessage(role=Role.ASSISTANT, content=response),
  File "/opt/conda/lib/python3.10/site-packages/pydantic/main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ChatMessage
content
  Input should be a valid string [type=string_type, input_value=('我是一个名为 Chat...答复和支持。')]), input_type=tuple]
    For further information visit https://errors.pydantic.dev/2.0.3/v/string_type

chatglm-6b 和 chatglm2-6b 的 chat 方法返回的 response 是一个包含当前轮 response 和 history 的 tuple，API 实现里面设置 ChatMessage 的 content 类型为 str，就出错了

**Comment by hiyouga** [comment]
所以你应该按照 API 的输入格式来构造数据，而不是 ChatGLM 的格式

**Comment by snachx** [comment]
是按照 API 的输入格式构造请求的，我不是说请求里面的问题，而是 API 后端处理请求的问题
https://github.com/hiyouga/ChatGLM-Efficient-Tuning/blob/d4d6250f6bc4e8cfec67d435b5551c324ed5bacd/src/glmtuner/api/app.py#L72
这里 response 是 tuple，但是直接传到了
https://github.com/hiyouga/ChatGLM-Efficient-Tuning/blob/d4d6250f6bc4e8cfec67d435b5551c324ed5bacd/src/glmtuner/api/app.py#L84
ChatMessage 要求 content 是 str，但是传入的 response 是 tuple，所以会报错

**Comment by hiyouga** [comment]
了解了，感谢反馈，更新下代码应该就没问题了
