### ISSUE TITLE
freeze 微调报错

### ISSUE THREAD

**Issue by DRZJ1** [hiyouga/ChatGLM-Efficient-Tuning#333]
用的是4张A10,一共90G，但是在freeze微调还是显示显存不够，能否量化，或者节省显存。
CUDA_VISIBLE_DEVICES=0,1,2,3
torchrun --nnodes=1 --nproc_per_node=4 --master_port="12345" /home/ubuntu/ChatGLM-Efficient-Tuning/src/train_bash.py \
    --model_name_or_path /home/ubuntu/ChatGLM2-6B/chatglm2-6b \
    --per_device_train_batch_size 4\
    --use_v2 \
    --do_train \
    --dataset  \nt_3.8\
    --dataset_dir /home/ubuntu/ChatGLM-Efficient-Tuning/data \
    --finetuning_type  freeze\
    --lora_rank 100 \
    --lora_alpha 9\
    --lora_dropout 0.05\
    --output_dir frz-chatglmv1 \
    --overwrite_cache \
    --overwrite_output_dir \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 2e-4 \
    --num_train_epochs 3.0 \
    --max_samples 37935 \
    --plot_loss \
    --fp16

**Comment by hiyouga** [comment]
Freeze 不支持量化

**Comment by DRZJ1** [comment]
请问freeze大概需要多少显存

**Comment by hiyouga** [comment]
可以尝试设置 `--num_layer_trainable 2`，默认是 3

**Comment by DRZJ1** [comment]
--use_v2 \参数加上去会报错。然后设置--num_layer_trainable 2，报错，不知道该怎么解决了：Traceback (most recent call last):
  File "/home/ubuntu/ChatGLM-Efficient-Tuning/src/train_bash.py", line 21, in <module>
    main()
  File "/home/ubuntu/ChatGLM-Efficient-Tuning/src/train_bash.py", line 8, in main
    run_sft(model_args, data_args, training_args, finetuning_args)
  File "/home/ubuntu/ChatGLM-Efficient-Tuning/src/glmtuner/tuner/sft/workflow.py", line 61, in run_sft
    train_result = trainer.train()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers/trainer.py", line 1888, in _inner_training_loop
    self.optimizer.step()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/accelerate/optimizer.py", line 133, in step
    self.scaler.step(self.optimizer, closure)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 372, in step
    assert len(optimizer_state["found_inf_per_device"]) > 0, "No inf checks were recorded for this optimizer."
AssertionError: No inf checks were recorded for this optimizer.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 12232) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/accelerate/commands/launch.py", line 970, in launch_command
    multi_gpu_launcher(args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by hiyouga** [comment]
可能是数据集有问题

**Comment by DRZJ1** [comment]
我试用alpaca_gpt4_data_en.json的数据集也不行，/(ㄒoㄒ)/~~

**Comment by DRZJ1** [comment]
我用合并前的模型不行，合并后的可以了

**Comment by DRZJ1** [comment]
我用合并前的模型可以，原始模型可以。合并后的不可以了
