### ISSUE TITLE
RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by jazzlee008** [hiyouga/ChatGLM-Efficient-Tuning#370]
使用export_model.py 导出合并LoRa的新权重后，载入成功，但是推理直接报错 expected scalar type Half but found Float
使用非合并原生模型+LoRa可以正常使用。

Details error:
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  2.88it/s]
欢迎使用 ChatGLM2-6B 模型，输入内容即可进行对话，clear 清空对话历史，stop 终止程序

用户:who are you?
Traceback (most recent call last):
  File "/home/jazzlee/coding/ChatGLM2-6B/cli_demo.py", line 63, in <module>
    main()
  File "/home/jazzlee/coding/ChatGLM2-6B/cli_demo.py", line 46, in main
    for response, history, past_key_values in model.stream_chat(tokenizer, query, history=history,
  File "/home/jazzlee/miniconda3/envs/glm2env/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/home/jazzlee/.cache/huggingface/modules/transformers_modules/export_output/modeling_chatglm.py", line 1311, in stream_chat
    for outputs in self.stream_generate(**inputs, **gen_kwargs):
  File "/home/jazzlee/miniconda3/envs/glm2env/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/home/jazzlee/.cache/huggingface/modules/transformers_modules/export_output/modeling_chatglm.py", line 1388, in stream_generate
    outputs = self(
              ^^^^^
  File "/home/jazzlee/miniconda3/envs/glm2env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jazzlee/.cache/huggingface/modules/transformers_modules/export_output/modeling_chatglm.py", line 1190, in forward
    transformer_outputs = self.transformer(
                          ^^^^^^^^^^^^^^^^^
  File "/home/jazzlee/miniconda3/envs/glm2env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jazzlee/.cache/huggingface/modules/transformers_modules/export_output/modeling_chatglm.py", line 996, in forward
    layer_ret = layer(
                ^^^^^^
  File "/home/jazzlee/miniconda3/envs/glm2env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jazzlee/.cache/huggingface/modules/transformers_modules/export_output/modeling_chatglm.py", line 624, in forward
    attention_input = self.input_layernorm(hidden_states)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jazzlee/miniconda3/envs/glm2env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jazzlee/miniconda3/envs/glm2env/lib/python3.11/site-packages/torch/nn/modules/normalization.py", line 190, in forward
    return F.layer_norm(
           ^^^^^^^^^^^^^
  File "/home/jazzlee/miniconda3/envs/glm2env/lib/python3.11/site-packages/torch/nn/functional.py", line 2515, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: expected scalar type Half but found Float

**Comment by hiyouga** [comment]
model = model.half()

**Comment by codemayq** [comment]
更新一下版本

**Comment by hiyouga** [comment]
@codemayq 这是推理时候的，不应该使用 fp16 参数，而是 model.half()
