### ISSUE TITLE
[BUG] PPO训练报错 RuntimeError: Expected all tensors to be on the same device

### ISSUE THREAD

**Issue by qinqinqaq** [hiyouga/ChatGLM-Efficient-Tuning#381]
run.sh
export CUDA_VISIBLE_DEVICES=0,1
accelerate launch --config_file scripts/qlora_ppo/accelerate_config.yaml src/train_bash.py \
    --stage ppo \
    --model_name_or_path /home/komove/fkb/project/chatglm_tuning/output/chat_glm_6B.V2023.2.2/merge_sft_step1 \
    --reward_model /home/komove/fkb/project/chatglm_tuning/output/chat_glm_6B.V2023.2.2/rm_test \
    --do_train \
    --max_samples 500 \
    --dataset 20230706_zh \
    --dataset_dir /home/komove/fkb/project/qlora_project/dataset/history_data/20230728/ \
    --overwrite_cache \
    --finetuning_type lora \
    --resume_lora_training False \
    --lora_rank 64 \
    --lora_alpha 32 \
    --lora_target query_key_value \
    --output_dir /home/komove/fkb/project/chatglm_tuning/output/chat_glm_6B.V2023.2.2/ppo \
    --per_device_train_batch_size 1 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 500 \
    --save_total_limit 5 \
    --learning_rate 1e-5 \
    --num_train_epochs 2.0 \
    --fp16 \
    --quantization_bit 4 \
    --plot_loss \
    --ddp_find_unused_parameters False \
    --gradient_accumulation_steps 16 \
    --max_source_length 512 \
    --max_target_length 1536 \
    --max_grad_norm 0.5 \

错误日志
Traceback (most recent call last):
  File "/home/komove/fkb/project/chatglm_tuning/src/train_bash.py", line 21, in <module>
    main()
  File "/home/komove/fkb/project/chatglm_tuning/src/train_bash.py", line 12, in main
    run_ppo(model_args, data_args, training_args, finetuning_args)
  File "/home/komove/fkb/project/chatglm_tuning/src/glmtuner/tuner/ppo/workflow.py", line 66, in run_ppo
    ppo_trainer.ppo_train(max_target_length=data_args.max_target_length)
  File "/home/komove/fkb/project/chatglm_tuning/src/glmtuner/tuner/ppo/trainer.py", line 122, in ppo_train
    stats = self.step(queries, responses, rewards)
  File "/home/komove/anaconda3/envs/chatglm/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/komove/anaconda3/envs/chatglm/lib/python3.9/site-packages/trl/trainer/ppo_trainer.py", line 621, in step
    all_logprobs, _, values, masks = self.batched_forward_pass(self.model, queries, responses, model_inputs)
  File "/home/komove/anaconda3/envs/chatglm/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/komove/fkb/project/chatglm_tuning/src/glmtuner/tuner/ppo/trainer.py", line 216, in batched_forward_pass
    logprobs = logprobs_from_logits(logits[:, :-1, :], input_ids[:, 1:])
  File "/home/komove/anaconda3/envs/chatglm/lib/python3.9/site-packages/trl/core.py", line 96, in logprobs_from_logits
    logpy = torch.gather(logp, 2, labels.unsqueeze(2)).squeeze(-1)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument index in method wrapper_CUDA_gather)
[2023-08-03 15:02:52,738] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 229107 closing signal SIGTERM
[2023-08-03 15:02:53,054] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 1 (pid: 229108) of binary: /home/komove/anaconda3/envs/chatglm/bin/python
Traceback (most recent call last):
  File "/home/komove/anaconda3/envs/chatglm/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/komove/anaconda3/envs/chatglm/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/komove/anaconda3/envs/chatglm/lib/python3.9/site-packages/accelerate/commands/launch.py", line 964, in launch_command
    deepspeed_launcher(args)
  File "/home/komove/anaconda3/envs/chatglm/lib/python3.9/site-packages/accelerate/commands/launch.py", line 687, in deepspeed_launcher
    distrib_run.run(args)
  File "/home/komove/anaconda3/envs/chatglm/lib/python3.9/site-packages/torch/distributed/run.py", line 788, in run
    elastic_launch(
  File "/home/komove/anaconda3/envs/chatglm/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/komove/anaconda3/envs/chatglm/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by kidd20172017** [comment]
解决了吗  我也遇到了，改了很多地方也没成功。
