### ISSUE TITLE
The latest code has some problems while training

### ISSUE THREAD

**Issue by OceannTwT** [hiyouga/ChatGLM-Efficient-Tuning#50]
Traceback (most recent call last):
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/train_ppo.py", line 125, in <module>
    main()
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/train_ppo.py", line 93, in main
    responses_with_queries = ppo_trainer.generate(queries, length_sampler=output_length_sampler, **gen_kwargs)
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/utils/ppo.py", line 162, in generate
    response = self.accelerator.unwrap_model(self.model).generate(
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/trl/models/modeling_value_head.py", line 195, in generate
    return self.pretrained_model.generate(*args, **kwargs)
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/peft/peft_model.py", line 731, in generate
    outputs = self.base_model.generate(**kwargs)
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/transformers/generation/utils.py", line 1454, in generate
    logits_processor = self._get_logits_processor(
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/transformers/generation/utils.py", line 935, in _get_logits_processor
    processors = self._merge_criteria_processor_list(processors, logits_processor)
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/transformers/generation/utils.py", line 957, in _merge_criteria_processor_list
    if len(custom_list) == 0:
TypeError: object of type 'InvalidScoreLogitsProcessor' has no len()

**Comment by hiyouga** [comment]
Sorry for the mistakes, we have fixed it in the lastest version.
