### ISSUE TITLE
多卡lora训练报错

### ISSUE THREAD

**Issue by ZTurboX** [hiyouga/ChatGLM-Efficient-Tuning#72]
多卡lora训练，刚开始能正常训练，跑了一会儿会报错

命令：
CUDA_VISIBLE_DEVICES=0,1 accelerate launch --config_file ./config.yml finetune.py \
    --do_train \
    --model_name_or_path ./chatglm-6b \
    --dataset article_gen \
    --dataset_dir ./data \
    --finetuning_type lora \
    --output_dir lora_output_article \
    --overwrite_cache \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 2 \
    --lr_scheduler_type cosine \
    --max_source_length 256 \
    --max_target_length 1500 \
    --logging_steps 10 \
    --save_steps 10000 \
    --learning_rate 1e-4 \
    --num_train_epochs 25.0 \
    --ddp_find_unused_parameters False \
    --fp16

报错信息：
WARNING:torch.distributed.elastic.agent.server.api:Received 1 death signal, shutting down workers
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 30482 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 30483 closing signal SIGHUP
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/chat_env/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/envs/chat_env/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/anaconda3/envs/chat_env/lib/python3.8/site-packages/accelerate/commands/launch.py", line 909, in launch_command
    multi_gpu_launcher(args)
  File "/usr/local/anaconda3/envs/chat_env/lib/python3.8/site-packages/accelerate/commands/launch.py", line 604, in multi_gpu_launcher
    distrib_run.run(args)
  File "/usr/local/anaconda3/envs/chat_env/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/anaconda3/envs/chat_env/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/anaconda3/envs/chat_env/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 241, in launch_agent
    result = agent.run()
  File "/usr/local/anaconda3/envs/chat_env/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/anaconda3/envs/chat_env/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 723, in run
    result = self._invoke_run(role)
  File "/usr/local/anaconda3/envs/chat_env/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 864, in _invoke_run
    time.sleep(monitor_interval)
  File "/usr/local/anaconda3/envs/chat_env/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 62, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 30463 got signal: 1

**Comment by hiyouga** [comment]
是否使用了 nohup？请避免使用 nohup。
https://github.com/pytorch/pytorch/issues/76894

**Comment by ZeyuTeng96** [comment]
> 是否使用了 nohup？请避免使用 nohup。 [pytorch/pytorch#76894](https://github.com/pytorch/pytorch/issues/76894)

不使用Nohup也报了这个错，怎么肥事

**Comment by ZTurboX** [comment]
> 是否使用了 nohup？请避免使用 nohup。 [pytorch/pytorch#76894](https://github.com/pytorch/pytorch/issues/76894)

用了nohup,如果不用nohup那怎样后台守护进程运行呢

**Comment by hiyouga** [comment]
> > 是否使用了 nohup？请避免使用 nohup。 [pytorch/pytorch#76894](https://github.com/pytorch/pytorch/issues/76894)
> 
> 用了nohup,如果不用nohup那怎样后台守护进程运行呢

请使用 tmux。

**Comment by hiyouga** [comment]
> > 是否使用了 nohup？请避免使用 nohup。 [pytorch/pytorch#76894](https://github.com/pytorch/pytorch/issues/76894)
> 
> 不使用Nohup也报了这个错，怎么肥事

说明在运行之前，端口已经被占用。

**Comment by ZeyuTeng96** [comment]
> > > 是否使用了 nohup？请避免使用 nohup。 [pytorch/pytorch#76894](https://github.com/pytorch/pytorch/issues/76894)
> > 
> > 
> > 不使用Nohup也报了这个错，怎么肥事
> 
> 说明在运行之前，端口已经被占用。

nccl的通信端口嘛？

**Comment by ZeyuTeng96** [comment]
> > > 是否使用了 nohup？请避免使用 nohup。 [pytorch/pytorch#76894](https://github.com/pytorch/pytorch/issues/76894)
> > 
> > 
> > 不使用Nohup也报了这个错，怎么肥事
> 
> 说明在运行之前，端口已经被占用。

但是，通信端口被占用的时候，不是会直接报一个port already used的错误嘛，为什么最后是一个WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1170 closing signal SIGTERM

**Comment by gladzhang** [comment]
使用accelerate的--main_process_port 29520， 重新指定端口号即可
