### ISSUE TITLE
While I tried to train RLHF by deepspeeed, it happens to some problem

### ISSUE THREAD

**Issue by OceannTwT** [hiyouga/ChatGLM-Efficient-Tuning#74]
Here is my training script:

```
MASTER_PORT=$(shuf -n 1 -i 10000-65535)

deepspeed --num_gpus=8 --master_port $MASTER_PORT src/train_ppo.py \
    --deepspeed deepspeed.json \
    --do_train \
    --dataset alpaca_gpt4_en \
    --finetuning_type lora \
    --reward_model path_to_rm_checkpoint \
    --output_dir path_to_ppo_checkpoint \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 5e-5 \
    --num_train_epochs 1.0 \
    --fp16

```

I got this issue when enter ppo training:

Traceback (most recent call last):
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/train_ppo.py", line 117, in <module>
    main()
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/train_ppo.py", line 54, in main
    ppo_trainer = PPOTrainerForChatGLM(
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/utils/ppo.py", line 135, in __init__
    super().__init__(*args, **kwargs)
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py", line 181, in __init__
    self.accelerator = Accelerator(
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/accelerate/accelerator.py", line 403, in __init__
    self.state.mixed_precision == "fp16"
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/accelerate/state.py", line 624, in mixed_precision
    config = self.deepspeed_plugin.deepspeed_config
AttributeError: 'NoneType' object has no attribute 'deepspeed_config'

I thought that should be a parameter without passing in Trainer, but I cannot figure out the trick to make it.I am in need of your support. 
Thanks for your help in advance.

**Comment by OceannTwT** [comment]
Could you provide some examples to use Accelerate on rlhf? How to set a Accelerate config? I am not so familiar with it...

**Comment by hiyouga** [comment]
Same as https://github.com/hiyouga/ChatGLM-Efficient-Tuning/blob/main/examples/ads_generation.md
