### ISSUE TITLE
Accelerate多卡Lora微调报错

### ISSUE THREAD

**Issue by YueGeek** [hiyouga/ChatGLM-Efficient-Tuning#75]
accelerate，2张4090，lora训练。之前能成功地多卡训练，0卡和1卡显存占用差不多都是20GB；重启后，再进行多卡训练时，报错，发现0卡和1卡显存占用差不多都是接近24GB了，请各位前辈指点一下。

命令：
accelerate launch src/finetune.py \
    --do_train \
    --dataset train \
    --finetuning_type lora \
    --output_dir lora_multi \
    --overwrite_cache \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --max_source_length 128 \
    --max_target_length 128 \
    --model_name_or_path /media/data/yw/data/THUDM/chatglm-6b \
    --lr_scheduler_type cosine \
    --logging_steps 50 \
    --save_steps 500 \
    --learning_rate 1e-5 \
    --num_train_epochs 3.0 \
    --lora_rank 32 \
    --ddp_find_unused_parameters False \
    --plot_loss \
    --fp16

报错信息：
**RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling \`cublasCreate(handle)\`**
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1535546 closing signal SIGTERM
**ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 1535547) of binary:** /media/data/anaconda3/envs/chatglm/bin/python
Traceback (most recent call last):
  File "/media/data/anaconda3/envs/chatglm/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/media/data/anaconda3/envs/chatglm/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/media/data/anaconda3/envs/chatglm/lib/python3.10/site-packages/accelerate/commands/launch.py", line 914, in launch_command
    multi_gpu_launcher(args)
  File "/media/data/anaconda3/envs/chatglm/lib/python3.10/site-packages/accelerate/commands/launch.py", line 603, in multi_gpu_launcher
    distrib_run.run(args)
  File "/media/data/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/media/data/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/media/data/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
**torch.distributed.elastic.multiprocessing.errors.ChildFailedError:** 

src/finetune.py FAILED
Failures:
  <NO_OTHER_FAILURES>
Root Cause (first observed failure):
[0]:
  time      : 2023-05-10_14:50:44
  host      : jo
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1535547)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by hiyouga** [comment]
可能是显存爆了，试试用更小的 batch size 或者进行模型量化

**Comment by hiyouga** [comment]
重启一下主机呢？可能之前的显存没有释放

**Comment by realdenis** [comment]
我也遇到了相同的问题，直接在加载预训练的模型时就报错了
<img width="670" alt="WechatIMG1375" src="https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/60921346/c69bc52e-d461-4a69-b498-60a2e51e66a0">

**Comment by YueGeek** [comment]
> 重启一下主机呢？可能之前的显存没有释放

重启了，还是报错，也不知道哪里有问题。之前多卡训练的好好的

**Comment by YueGeek** [comment]
> 我也遇到了相同的问题，直接在加载预训练的模型时就报错了。单卡跑一切正常。 <img alt="WechatIMG1375" width="670" src="https://user-images.githubusercontent.com/60921346/237381314-c69bc52e-d461-4a69-b498-60a2e51e66a0.png">

我的是在开始训练的时候的出错的，数据加载和模型加载过程能正常运行

**Comment by LebronJames0423** [comment]
当前使用的命令：
accelerate launch src/train_sft.py     --do_train     --dataset alpaca_gpt4_zh     --finetuning_type lora     --output_dir alpacagpt4_zh_lora     --overwrite_cache     --per_device_train_batch_size 1     --gradient_accumulation_steps 2     --lr_scheduler_type cosine     --logging_steps 10     --save_steps 2000     --learning_rate 1e-3     --num_train_epochs 2.0     --lora_rank 32     --ddp_find_unused_parameters False     --plot_loss     --fp16

报错如下：
  0%|                                                                                                                                                                                                          | 0/24408 [00:00<?, ?it/s]Traceback (most recent call last):
  File "src/train_sft.py", line 100, in <module>
    main()
  File "src/train_sft.py", line 68, in main
    train_result = trainer.train()
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/transformers/trainer.py", line 1664, in train
    return inner_training_loop(
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/transformers/trainer.py", line 1938, in _inner_training_loop
Traceback (most recent call last):
  File "src/train_sft.py", line 100, in <module>
    main()
      File "src/train_sft.py", line 68, in main
tr_loss_step = self.training_step(model, inputs)
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/transformers/trainer.py", line 2735, in training_step
    train_result = trainer.train()
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/transformers/trainer.py", line 1664, in train
    return inner_training_loop(
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/transformers/trainer.py", line 1938, in _inner_training_loop
    loss = self.compute_loss(model, inputs)
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/transformers/trainer.py", line 2767, in compute_loss
    tr_loss_step = self.training_step(model, inputs)
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/transformers/trainer.py", line 2735, in training_step
    outputs = model(**inputs)
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    loss = self.compute_loss(model, inputs)
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/transformers/trainer.py", line 2767, in compute_loss
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    outputs = model(**inputs)
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/peft/peft_model.py", line 678, in forward
    return forward_call(*args, **kwargs)
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    return self.base_model(
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return forward_call(*args, **kwargs)
  File "/home/lw/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/1d240ba371910e9282298d4592532d7f0f3e9f3e/modeling_chatglm.py", line 1190, in forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    transformer_outputs = self.transformer(
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/peft/peft_model.py", line 678, in forward
    return forward_call(*args, **kwargs)
  File "/home/lw/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/1d240ba371910e9282298d4592532d7f0f3e9f3e/modeling_chatglm.py", line 985, in forward
    return self.base_model(
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    layer_ret = torch.utils.checkpoint.checkpoint(
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/autograd/function.py", line 506, in apply
    return forward_call(*args, **kwargs)
  File "/home/lw/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/1d240ba371910e9282298d4592532d7f0f3e9f3e/modeling_chatglm.py", line 1190, in forward
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    transformer_outputs = self.transformer(
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lw/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/1d240ba371910e9282298d4592532d7f0f3e9f3e/modeling_chatglm.py", line 627, in forward
    attention_outputs = self.attention(
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lw/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/1d240ba371910e9282298d4592532d7f0f3e9f3e/modeling_chatglm.py", line 985, in forward
    layer_ret = torch.utils.checkpoint.checkpoint(
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return forward_call(*args, **kwargs)
  File "/home/lw/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/1d240ba371910e9282298d4592532d7f0f3e9f3e/modeling_chatglm.py", line 445, in forward
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/autograd/function.py", line 506, in apply
    mixed_raw_layer = self.query_key_value(hidden_states)
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/peft/tuners/lora.py", line 565, in forward
    return forward_call(*args, **kwargs)
  File "/home/lw/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/1d240ba371910e9282298d4592532d7f0f3e9f3e/modeling_chatglm.py", line 627, in forward
    result = F.linear(x, transpose(self.weight, self.fan_in_fan_out), bias=self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
    attention_outputs = self.attention(
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lw/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/1d240ba371910e9282298d4592532d7f0f3e9f3e/modeling_chatglm.py", line 445, in forward
    mixed_raw_layer = self.query_key_value(hidden_states)
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/peft/tuners/lora.py", line 565, in forward
    result = F.linear(x, transpose(self.weight, self.fan_in_fan_out), bias=self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
  0%|                                                                                                                                                                                                          | 0/24408 [00:00<?, ?it/s]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 39886) of binary: /home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/bin/python
Traceback (most recent call last):
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/accelerate/commands/launch.py", line 909, in launch_command
    multi_gpu_launcher(args)
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/accelerate/commands/launch.py", line 604, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/lw/project/2023/PyCharmProject/ChatGLM-Efficient-Tuning/venv/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
src/train_sft.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-06-05_17:57:46
  host      : d0629_15u
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 39887)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-05_17:57:46
  host      : d0629_15u
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 39886)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html


请问是什么原因呢？

**Comment by hiyouga** [comment]
@LebronJames0423 是什么显卡？可能是爆显存了。

**Comment by LebronJames0423** [comment]
> @LebronJames0423 是什么显卡？可能是爆显存了。

2块 v100 单块16G

**Comment by hiyouga** [comment]
@LebronJames0423 设置 `--lora_rank 8 --max_source_length 256 --max_target_length 256` 试试。

**Comment by LebronJames0423** [comment]
> @LebronJames0423 设置 `--lora_rank 8 --max_source_length 256 --max_target_length 256` 试试。

可以跑起来了，谢谢
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/33833521/0c79973a-4e6d-4738-b010-03fe939f52cf)

**Comment by liuyijiang1994** [comment]
> > 我也遇到了相同的问题，直接在加载预训练的模型时就报错了。单卡跑一切正常。 <img alt="WechatIMG1375" width="670" src="https://user-images.githubusercontent.com/60921346/237381314-c69bc52e-d461-4a69-b498-60a2e51e66a0.png">
> 
> 我的是在开始训练的时候的出错的，数据加载和模型加载过程能正常运行

请问解决了么 遇到了一样的问题
