### ISSUE TITLE
想用长文本数据微调模型

### ISSUE THREAD

**Issue by tu2022** [hiyouga/ChatGLM-Efficient-Tuning#90]
想问一下，如果max_source_lenghth 长度需要1024（后来测试下降到700的最大长度，依然不行）需要多少显存？我用了四张v100，32g的卡还是显示显存不足，我在accelerate设置num_processes为8，想用8张卡，但是直接报错,不知道为什么

**Comment by hiyouga** [comment]
显存不足应降低 batch size。
多卡详细报错信息发一下。

**Comment by tu2022** [comment]
> 显存不足应降低 batch size。 多卡详细报错信息发一下。

我batch size 已经调成1了依然显示内存不足，多卡报错信息如下（我只要用大于4张卡运行就会有问题，但是用4张卡运行就不会报错）：
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1761 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 0 (pid: 1759) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 903, in launch_command
    deepspeed_launcher(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 648, in deepspeed_launcher
    distrib_run.run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
====================================================
src/finetune.py FAILED

这会和我在镜像中微调的模型有关系吗

**Comment by hiyouga** [comment]
可能和 transformers 版本或 CUDA 环境有关，我也不太清楚问题原因。
